const ability = (trigger, effects, costs = [], extra = {}) => ({ trigger, effects, costs, ...extra });
const effect = (type, data = {}) => ({ type, ...data });

/**
 * Canonical rules for cards whose printed text is not safely expressible by the
 * legacy text parser. These definitions are data, not card-specific executable
 * code, and may later be loaded directly from Supabase.
 */
export const explicitCardRules = Object.freeze({
  p3: [ability("static", [effect("keyword", { keyword: "Voar" })]), ability("activated", [effect("transformFromHandOrDeck", { name: "Valorian, o Dragão Verdadeiro", replaceSelf: true, shuffle: true })], [{ type: "energy", amount: 10 }], { uiActivation: true })],
  p5: [ability("static", [effect("keyword", { keyword: "Voar" }), effect("keyword", { keyword: "Indomável" })]), ability("onCombatDamage", [effect("damageAdjacent", { amount: 1, relation: "combatDefender" })])],
  p20: [ability("activated", [effect("gainMaxEnergy", { amount: 1 }), effect("destroy", { target: "self" })], [{ type: "tap", amount: 1 }], { uiActivation: true })],
  p15: [ability("onPlay", [effect("conditionalDrawByControlledSubtype", { subtype: "Dragão", ifTrue: 2, ifFalse: 1 })])],
  p16: [ability("onPlay", [effect("modifyStats", { target: "anyCreature", requiredSubtype: "Dragão", attack: 0, health: 2, duration: "turn" })])],
  p6: [ability("onEnter", [effect("damage", { amount: 2, target: "anyCreature", selections: 1 })])],
  p9: [ability("static", [effect("protectAlliedDragonsOncePerTurn")])],
  p10: [ability("static", [effect("keyword", { keyword: "Atropelar" })]), ability("onDestroyed", [effect("damageAll", { amount: 2, target: "allCreatures" })])],
  p12: [ability("onPlay", [effect("createImage", { name: "Dragão Filhote", destination: "field" })])],
  p13: [ability("onPlay", [effect("replaceImage", { oldName: "Dragão Filhote", newName: "Dragão Jovem" })])],
  p14: [ability("onPlay", [effect("replaceImage", { oldName: "Dragão Jovem", newName: "Dragão Ancião" })])],
  p17: [ability("onPlay", [effect("forceAttack", { attacker: { controller: "self", subtype: "Dragão", ready: true }, defender: "anyCreature" })])],
  p19: [ability("static", [effect("attachedStats", { attack: 0, health: 2 }), effect("conditionalAttachedBonus", { requiredSubtype: "Dragão", keyword: "Defensor" })])],
  p21: [ability("static", [effect("attachedKeyword", { keyword: "Voar" }), effect("conditionalAttachedBonus", { requiredSubtype: "Dragão", attack: 2, health: 0 })])],
  p22: [ability("onCreatureDestroyed", [effect("createImage", { name: "Dragão Filhote", destination: "field" })], [], { condition: { all: [{ eventCardTypeNot: "Imagem" }, { eventCardSubtype: "Dragão" }] } })],
  p23: [ability("onEnter", [effect("damage", { amount: 1, target: "anyCreature", selections: 1 })])],
  p24: [ability("static", [effect("keyword", { keyword: "Voar" })]), ability("onEnter", [effect("damage", { amount: 3, target: "anyCreature", selections: 1 }), effect("damageAdjacent", { amount: 1, relation: "selectedTarget" })])],
  p25: [ability("static", [effect("keyword", { keyword: "Voar" })]), ability("onEnter", [effect("damage", { amount: 5, target: "anyCreature", selections: 1 }), effect("damageAdjacent", { amount: 2, relation: "selectedTarget" })])],
  p27: [ability("onEnter", [effect("grantNextCardDiscount", { amount: 1, duration: "turn" })])],
  p30: [ability("onPlay", [effect("modifyStatsFromTurnCardsPlayed", { target: "self", attackPerCard: 1, healthPerCard: 1, duration: "permanent" })], [], { condition: { cardsPlayedBeforeThisAtLeast: 1 } })],
  p32: [ability("static", [effect("keyword", { keyword: "Veloz" })]), ability("onPlay", [effect("destroyCreatureUpToTurnCardsPlayed")], [], { condition: { cardsPlayedBeforeThisAtLeast: 1 } })],
  p29: [ability("onPlay", [effect("keyword", { keyword: "Investida" }), effect("modifyStats", { target: "self", attack: 1, health: 0, duration: "permanent" })], [], { condition: { cardsPlayedBeforeThisAtLeast: 1 } })],
  p31: [ability("onPlay", [effect("damage", { amount: 2, target: "anyCharacter", selections: 1 })], [], { condition: { cardsPlayedBeforeThisAtLeast: 1 } })],
  p33: [ability("onCardPlayed", [effect("draw", { amount: 1 })], [], { condition: { eventOwnerIsController: true, eventCardKeyword: "Fura-fila" }, triggerMeta: { kind: "conditional-passive", scenario: "Sempre que você jogar uma carta com Fura-fila." } })],
  p34: [ability("onEnter", [effect("damageAndMarkRepeat", { amount: 1, target: "anyCreature", selections: 1 })]), ability("onCreatureDestroyed", [effect("damageAndMarkRepeat", { amount: 1, target: "anyCreature", selections: 1 })], [], { condition: { eventKilledBySource: true }, triggerMeta: { kind: "conditional-passive", scenario: "Se a criatura que recebeu o dano de Bafo de Fumaça morrer, repita o efeito." } })],
  p44: [ability("onPlay", [effect("gainEnergy", { amount: 1, destination: "main" }), effect("disableReserveStorage", { duration: "turn" })])],
  p37: [ability("activated", [effect("damageFromSacrificedAttack", { target: "anyCharacter", selections: 1 })], [{ type: "sacrifice", amount: 1, subtype: "Goblin" }], { uiActivation: true, usageLimit: { count: 1, period: "turn" } })],
  p38: [
    ability("onEnter", [effect("validateAttachedSubtype", { subtype: "Goblin" }), effect("attachedStats", { attack: 2, health: 0 }), effect("attachedKeyword", { keyword: "Veloz" })]),
    ability("activated", [effect("reattachArtifact", { target: "allyCreature", requiredSubtype: "Goblin", selections: 1, subtype: "Goblin", attack: 2, keyword: "Veloz", excludeCurrentAttachment: true })], [], { uiActivation: true, usageLimit: { count: 1, period: "turn" }, triggerMeta: { kind: "activated", scenario: "No seu turno, equipe em outro Goblin aliado." } }),
    ability("onAttachedHostDestroyed", [effect("optionalReequipArtifact", { energyCost: 2, subtype: "Goblin", attack: 2, keyword: "Veloz" })], [], { triggerMeta: { kind: "conditional-passive", scenario: "Quando o Goblin equipado for destruído." } })
  ],
  p39: [ability("onPermanentLeaves", [effect("addMarker", { target: "self", marker: "action", amount: 1 })], [], { condition: { eventOwnerIsController: true, eventCardSubtype: "Goblin", controllerTurn: true } }), ability("activated", [effect("createImage", { name: "SUPER MEGATANQUE CHUMBO 3000", destination: "field", temporaryUntilTurnEnd: true })], [{ type: "removeMarkers", marker: "action", amount: 5 }], { uiActivation: true })],
  p35: [ability("onCreatureEnter", [effect("damage", { amount: 1, target: "anyCharacter", selections: 1 })], [], { condition: { eventOwnerIsController: true, eventCardSubtype: "Goblin", otherThanSource: true }, triggerMeta: { kind: "conditional-passive", scenario: "Sempre que você invocar um Goblin." } })],
  p36: [ability("onEnter", [effect("returnNamedFromGraveToHand", { name: "Suborno" })]), ability("onPlay", [effect("grantUntilTurnEnd", { ability: ability("onDestroyed", [effect("returnSelfToHand")]) })], [], { condition: { cardsPlayedBeforeThisAtLeast: 1 } })],
  p42: [ability("onPlay", [effect("draw", { amount: 1 })])],
  p41: [ability("onPlay", [effect("returnAllyToHandWithComboDiscount", { target: "allyCreature", selections: 1, amount: 1, duration: "turn" })])],
  p43: [ability("onPlay", [effect("grantNextCardDiscount", { amount: 2, typeNot: "Criatura", duration: "turn" })])],
  p45: [ability("onPlay", [effect("damageFromCardsPlayedThisTurn", { target: "anyCreature", selections: 1 })])],
  p46: [ability("onPlay", [effect("remainUntilTurnEnd"), effect("trackCardsPlayedAfterSelf")]), ability("onTurnEnd", [effect("countedChoice", { counter: "cardsPlayedAfterSelf", branches: [{ min: 1, max: 4, effects: [effect("damageHeroPerCount", { target: "controller", amount: 1 })] }, { min: 5, max: 5, effects: [effect("createImage", { name: "BUCHA DE CANHÃO", destination: "field" })] }, { min: 6, max: 6, effects: [effect("createImage", { name: "TRAMBUCO DE PIPOCO", destination: "field" })] }, { min: 7, effects: [effect("createImage", { name: "CARCAÇA CHUMBADA DE TANQUE", destination: "field" })] }] }), effect("moveSelf", { destination: "grave" })])],
  p47: [ability("onPlay", [effect("remainUntilTurnEnd")]), ability("onPermanentLeaves", [effect("gainEnergy", { amount: 1, destination: "main" })], [], { condition: { eventOwnerIsController: true, eventCardSubtype: "Goblin", controllerTurn: true } }), ability("onTurnEnd", [effect("moveSelf", { destination: "grave" })])],
  p48: [ability("onPlay", [effect("resurrect", { zone: "grave", cardType: "Criatura", subtype: "Goblin", destination: "field" }), effect("configureResurrected", { grantKeywordIfCombo: "Investida", destroyAtTurnEnd: true })], [], { playCondition: { controllerGraveHasSubtype: "Goblin" } })],
  p49: [ability("onCardPlayed", [effect("applyGoblinThresholds")])],
  p54: { hero: true, evolution: [{ level: 2, condition: { spellsCastAtLeast: 4 } }, { level: 3, condition: { spellsCastAtLeast: 8 } }], levels: { 1: [ability("onTurnEnd", [effect("resolveLastSpellElement")], [], { condition: { eventOwnerIsController: true } })], 2: [ability("static", [effect("costModifier", { selector: { controller: "self", type: "Feitiço", zone: "hand" }, amount: -1, firstEachTurn: true })])], 3: [ability("onTurnEnd", [effect("repeatLastSpell")], [], { condition: { eventOwnerIsController: true } })] } },
  p57: [ability("onPlay", [effect("reduceEnemyAttackUntilControllerMaintenance", { amount: 2 }), effect("grantNextElementEffect", { element: "Fogo", keyword: "Sufocado", duration: "untilNextTurn" })])],
  p64: [ability("onPlay", [effect("damageByAdjacentCount", { target: "anyCreature", selections: 1, baseAmount: 1, perAdjacent: 1 }), effect("grantNextElementEffect", { element: "Água", keyword: "Congelado", duration: "untilNextTurn" })])],
  p79: [ability("onSpellCast", [effect("draw", { amount: 1 })], [], { condition: { eventOwnerIsController: true, controllerTurn: true, firstEachTurn: true }, usageLimit: { count: 1, period: "turn" } })],
  p59: [ability("static", [effect("costModifier", { selector: { controller: "self", type: "Feitiço", zone: "hand" }, amount: -1, during: "controllerTurn" })])],
  p58: [ability("onPlay", [effect("damageAll", { amount: 0, amountPerEnemyCreature: 1, target: "allCreatures" })])],
  p71: [ability("onSpellCast", [effect("gainEnergy", { amount: 1, destination: "reserve" })], [], { condition: { firstEachTurn: true, spellElement: "Ar" } })],
  p72: [ability("onSpellCast", [effect("heal", { amount: 3, target: "controllerHero" })], [], { condition: { firstEachTurn: true, spellElement: "Água" } })],
  p63: [ability("onPlay", [effect("freezeEnemyBoard", { damageAlreadyFrozen: 2 })])],
  p61: [ability("onPlay", [effect("createImage", { name: "Clone de Água", destination: "field" }), effect("grantNextElementEffect", { element: "Ar", keyword: "Atordoado", duration: "untilNextTurn" })])],
  p62: [ability("onPlay", [effect("grantCharacterDamageShield", { target: "anyCharacter", selections: 1, uses: 1, duration: "turn" }), effect("grantNextElementEffect", { element: "Ar", keyword: "Atordoado", duration: "untilNextTurn" })])],
  p67: [ability("onPlay", [effect("consumeAllEnergyForDamage", { target: "anyCreature", selections: 1 })])],
  p70: [ability("onPlay", [effect("moveSelf", { destination: "grave" }), effect("controllerChoice", { choices: [[effect("createUniqueImage", { name: "Maestria Elemental: Piromancia" })], [effect("createUniqueImage", { name: "Maestria Elemental: Hidromancia" })], [effect("createUniqueImage", { name: "Maestria Elemental: Geomancia" })], [effect("createUniqueImage", { name: "Maestria Elemental: Aeromancia" })]] })])],
  p73: [ability("onSpellCast", [effect("geomancyChoice", { amount: 3, minimum: 1 })], [], { condition: { firstEachTurn: true, spellElement: "Terra" } })],
  p77: [ability("onEnter", [effect("grantNextCardDiscount", { amount: 1, typeOnly: "Feitiço", duration: "turn" })])],
  p80: [ability("onSpellCast", [effect("addMarker", { target: "self", marker: "action", amount: 1 })]), ability("activated", [effect("search", { zone: "deck", destination: "hand", types: ["Feitiço"], maxCostFromMarkerAmount: true, amount: 1, shuffle: true })], [{ type: "removeMarkers", marker: "action", amount: "X", minimum: 1 }], { uiActivation: true, usageLimit: { count: 1, period: "turn" } })],
  p87: [ability("onPlay", [effect("controllerChoice", { choices: [[effect("createImage", { name: "Ignis, a Chama Eterna", destination: "field" })], [effect("createImage", { name: "Terron, o Guardião Ancestral", destination: "field" })], [effect("createImage", { name: "Undaris, a Voz do Oceano", destination: "field" })], [effect("createImage", { name: "Zephyrus, o Relâmpago Voraz", destination: "field" })]] })])],
  p88: [ability("onEnter", [effect("snapshotStatsFromHand", { attackPerCard: 1, healthPerCard: 1 })])],
  p89: [ability("onMaintenance", [effect("optionalDrawWithCreatureCostDamage")], [], { condition: { eventOwnerIsController: true } })],
  p92: [ability("onEnter", [effect("snapshotHealthFromFactionConstants", { faction: "Divino" })])],
  p94: [ability("onPlay", [effect("search", { zone: "deck", destination: "field", types: ["Terreno"], amount: 1, shuffle: true })])],
  p84: { ignored: true, reason: "removed-from-game" },
  p85: { ignored: true, reason: "removed-from-game" },
  p93: { ignored: true, reason: "removed-from-game" },
  p99: { ignored: true, reason: "removed-from-game" },
  p101: { ignored: true, reason: "removed-from-game" },
  p97: [ability("onPlay", [effect("counterPendingAction")])],
  p102: [ability("onPlay", [effect("resurrect", { zone: "grave", cardType: "Criatura", maxCost: 5, destination: "field", choose: true })])],
  p105: [ability("activated", [effect("destroy", { target: "enemyPermanent", cardType: "Artefato", selections: 1 }), effect("destroy", { target: "self", cannotBePrevented: true })], [{ type: "tap", amount: 1 }], { uiActivation: true })],
  p116: [ability("onDestroyed", [effect("gainEnergy", { amount: 1, destination: "reserve" })])],
  p107: [ability("activated", [effect("grantTeamReserveTapAbility", { duration: "turn" }), effect("destroy", { target: "self" })], [{ type: "energy", amount: 1 }], { uiActivation: true })],
  p117: [ability("static", [effect("keyword", { keyword: "Atropelar" })]), ability("onEnter", [effect("optionalSacrificeBuff", { maximum: 3, attackPerCreature: 2 })])],
  p114: [ability("onCreatureDestroyed", [effect("modifyStats", { target: "self", attack: 1, health: 0, duration: "turn" })], [], { condition: { eventOwnerIsController: true, otherThanSource: true } })],
  p115: [ability("static", [effect("keyword", { keyword: "Investida" }), effect("keyword", { keyword: "Indomável" }), effect("cannotDefend")])],
  p120: [ability("onCombatKill", [effect("resurrect", { zone: "grave", cardType: "Criatura", cost: 1, destination: "field", optional: true })]), ability("onDestroyed", [effect("destroy", { target: "otherAllyCreature", selections: 1, optional: true }), effect("returnSelfToField", { onlyIfPreviousPaid: true })])],
  p119: [ability("onDestroyed", [effect("damageHeroFromTurnDeaths", { target: "enemyHero" })])],
  p126: [ability("onCreatureDestroyed", [effect("addMarker", { target: "self", marker: "action", amount: 1 })], [], { condition: { eventOwnerIsController: true } }), ability("activated", [effect("resurrectByDoubleMarkerCost", { cardType: "Criatura" })], [], { uiActivation: true })],
  p127: [ability("activated", [effect("replayTopGraveAbility", { trigger: "onDestroyed", requireType: "Criatura" })], [], { uiActivation: true, usageLimit: { count: 1, period: "turn" }, availability: { topGraveHasTrigger: "onDestroyed" } })],
  p130: [ability("onEnter", [effect("loseLife", { amount: 3, target: "controllerHero" })])],
  p133: [ability("static", [effect("keyword", { keyword: "Atropelar" })]), ability("onEnter", [effect("loseLife", { amount: 4, target: "controllerHero" })])],
  p134: [ability("onMaintenance", [effect("loseLife", { amount: 2, target: "controllerHero" }), effect("addMarker", { target: "self", marker: "action", amount: 1 })], [], { condition: { eventOwnerIsController: true } }), ability("activated", [effect("healFromMarkersRemoved", { target: "controllerHero" })], [{ type: "removeMarkers", marker: "action", amount: "X", minimum: 1 }], { uiActivation: true, usageLimit: { count: 1, period: "turn" } })],
  p135: [ability("onEnter", [effect("draw", { amount: 1 }), effect("loseLife", { amount: 4, target: "controllerHero" }), effect("replaceFirstAct", { effects: [effect("search", { zone: "deck", destination: "hand", types: ["Criatura"], subtype: "Vampiro", minCost: 4, amount: 1, shuffle: true })] })])],
  p139: [ability("onEnter", [effect("heal", { amount: 4, target: "controllerHero" })])],
  p124: [ability("onPlay", [effect("grantKeyword", { target: "anyCreature", requiredSubtype: "Malorga", keyword: "Toque da Morte", duration: "turn" })])],
  p125: [ability("onPlay", [effect("modifyStats", { target: "anyCreature", attack: 2, health: 0, duration: "turn" })])],
  p137: [ability("onDestroyed", [effect("heal", { amount: 4, target: "controllerHero" })]), ability("activated", [effect("grantKeyword", { target: "self", keyword: "Toque da Morte", duration: "turn" })], [{ type: "life", amount: 3 }], { uiActivation: true, usageLimit: { count: 1, period: "turn" } })],
  p138: [ability("activated", [effect("grantKeyword", { target: "self", keyword: "Veloz", duration: "turn" })], [{ type: "life", amount: 2 }], { uiActivation: true, usageLimit: { count: 1, period: "turn" } })],
  p141: [ability("activated", [effect("modifyStats", { target: "attachedCreature", attack: 2, health: 0, duration: "turn" })], [{ type: "tap", amount: 1 }, { type: "life", amount: 2 }], { uiActivation: true, usageLimit: { count: 1, period: "turn" } })],
  p142: [ability("onPlay", [effect("grantSubtype", { target: "anyCreature", subtype: "Vampiro", duration: "turn" }), effect("combatRestriction", { cannotCombatSubtype: "Vampiro", duration: "turn", relation: "selectedTarget" })])],
  p143: [ability("onPlay", [effect("destroy", { target: "anyCreature", requiredSubtype: "Vampiro", selections: 1 }), effect("heal", { amount: 4, target: "controllerHero" })])],
  p146: [ability("onPlay", [effect("nextCreaturePaysLife", { duration: "turn" })])],
  p147: [ability("onPlay", [effect("suffocateWhileSourceInField", { target: "anyPermanent", selections: 1 })]), ability("onTurnEnd", [effect("payLifeOrDestroySelf", { amount: 2 })], [], { condition: { eventOwnerIsController: true } }), ability("onPermanentLeaves", [effect("releaseSuffocatedBySource")])],
  p148: [ability("onLifeLost", [effect("resolveCrimsonCastle")], [], { condition: { eventOwnerIsController: true, controllerTurn: true } })],
  p149: [ability("onEnter", [effect("discard", { amount: 2, target: "controller" })])],
  p150: [ability("onPlay", [effect("linkCreatures", { target: "anyCreature", selections: 1 })]), ability("onPermanentLeaves", [effect("followLinkedDestination")])],
  p151: [ability("onPlay", [effect("replaySelectedAbility", { selector: { controller: "self", type: "Criatura", hasTrigger: "onEnter" }, trigger: "onEnter" })], [], { playCondition: { alliedPermanentHasTrigger: "onEnter" } })],
  p152: { hero: true, evolution: [{ level: 2, condition: { heroMarkersAtLeast: 3 } }, { level: 3, condition: { heroMarkersAtLeast: 6 } }], levels: { 1: [ability("onAttack", [effect("addMarker", { target: "hero", marker: "command", amount: 1 })], [], { condition: { sourceIsCommander: true } }), ability("static", [effect("commanderRule", { centerSlot: 2, attack: 2 })])], 2: [ability("static", [effect("commanderRule", { centerSlot: 2, attack: 3, keyword: "Atropelar" })])], 3: [ability("static", [effect("commanderCombatReplacement")])] } },
  p153: [ability("activated", [effect("gainTemporaryEnergy", { amount: 2 }), effect("skipNextMaxEnergyIncrease"), effect("destroy", { target: "self" })], [{ type: "tap", amount: 1 }], { uiActivation: true })],
  p154: [ability("onAttachedCreatureTargeted", [effect("draw", { amount: 1 })]), ability("static", [effect("graveReplacement", { destination: "obscuro" })])],
  p155: [ability("static", [effect("attachedStats", { attack: 3, health: 0 }), effect("attachedKeyword", { keyword: "Indomável" })])],
  p156: [ability("static", [effect("keyword", { keyword: "Robusto" })])],
  p157: [ability("onPlay", [effect("grantAdditionalAttack", { target: "anyCreature", amount: 1, duration: "turn" }), effect("scheduleEffect", { timing: "turnEnd", effect: effect("destroy", { target: "selected" }) })])],
  p158: [ability("onPlay", [effect("destroyExhaustedAndHealCost", { target: "anyCreature", requireExhausted: true, selections: 1 })])],
  p159: [ability("onPlay", [effect("suffocateUntilTurnEndAndDrawOwner", { target: "anyPermanent", selections: 1 })])],
  p160: [ability("onPlay", [effect("destroyIfDamagedControllerThisTurn", { target: "anyCreature", selections: 1 })])],
  p161: [ability("onPlay", [effect("destroyAtTurnEndUnlessCombat", { target: "anyCreature", selections: 1 })])],
  p163: [ability("onCombatStart", [effect("openRepositionWindow", { players: "both", moveAttachments: true, endsBy: ["bothConfirm", "responseTimeout"] })])],
  p165: [ability("onDamageTaken", [effect("modifyStats", { attack: 1, health: 0, duration: "permanent", target: "self" })], [], { condition: { sourceSurvived: true } })],
  p166: [ability("static", [effect("spellTargetSurcharge", { amount: 1 })])],
  p167: [ability("static", [effect("conditionalStats", { attack: 1, health: 0, condition: "controllerTurn" })])],
  p168: [ability("onOpponentSpellAttempt", [effect("opponentChoice", { firstEachTurn: true, choices: [[effect("loseLife", { amount: 1, target: "spellControllerHero" })], [effect("draw", { amount: 1, target: "chosenOtherPlayer" })]] })])],
  p169: [ability("static", [effect("keyword", { keyword: "Alerta" })])],
  p170: [ability("onEnter", [effect("banishUntilSourceLeaves", { target: "anyCreature", selections: 1 })]), ability("onPermanentLeaves", [effect("returnBanishedBySource")])],
  p173: [ability("onCreatureDestroyed", [effect("modifyStats", { target: "self", attack: 1, health: 1, duration: "permanent" })], [], { condition: { eventOwnerIsOpponent: true, controllerTurn: true }, usageLimit: { count: 1, period: "turn" } })],
  p174: [ability("onCombatStart", [effect("peekTop", { players: "both" }), effect("controllerChoice", { choices: [[effect("draw", { amount: 1, target: "bothPlayers" })], [effect("moveTopToBottom", { target: "bothPlayers" })]] })])],
  p176: [ability("static", [effect("keyword", { keyword: "Indomável" }), effect("cannotDefend")]), ability("onCombatKill", [effect("grantAdditionalAttack", { target: "self", amount: 1, duration: "turn" })], [], { usageLimit: { count: 1, period: "turn" } })],
  p178: { ignored: true, reason: "removed-from-game" },
  p179: [ability("onCardsDrawn", [effect("opponentChoice", { choices: [[effect("loseLifeFromCardsDrawn")], [effect("revealDrawnCards")]] })], [], { condition: { eventOwnerIsOpponent: true, outsideMaintenance: true } })],
  p181: [ability("static", [effect("recruitFirstActOnLeave")])],
  p182: [ability("static", [effect("doubleRecruitFirstAct")])],
  p183: [ability("onEnter", [effect("conditionalStats", { target: "allyCreature", health: 2, alternate: { targetName: "Recruta Elegante", health: 3 }, duration: "turn" })])],
  p184: [ability("onEnter", [effect("toggleTap", { target: "anyCreature" })])],
  p185: [ability("onEnter", [effect("snapshotStats", { target: "self", attackPerOtherSubtype: { subtype: "Recruta", amount: 1 } })])],
  p186: [ability("onEnter", [effect("modifyStats", { target: "allyCreature", attack: 2, health: 0, duration: "turn" })])],
  p188: [ability("onEnter", [effect("damage", { amount: 1, additionalIfExhausted: 1, target: "anyCharacter", selections: 1 })])],
  p190: [ability("onEnter", [effect("returnToHand", { target: "anyCreature", requireExhausted: true, selections: 1 })])],
  p191: [ability("onPlay", [effect("returnToHand", { target: "allyCreature", maxCost: 3, selections: 1 })])],
  p192: [ability("static", [effect("modifyStats", { attack: 2, health: -1, duration: "attached" }), effect("attachedConditionalKeyword", { attachedName: "Recruta Pinguço", keyword: "Barreira Mágica", duration: "attached" })])],
  p193: [ability("static", [effect("modifyStats", { attack: 3, health: 2, duration: "permanent" })])],
  p194: [ability("static", [effect("modifyStats", { attack: 1, health: 1, duration: "permanent" }), effect("keyword", { keyword: "Suporte +1/+1" })])],
  p195: [ability("static", [effect("modifyStats", { attack: 1, health: 4, duration: "permanent" }), effect("keyword", { keyword: "Defensor 2" })])],
  p196: [ability("static", [effect("modifyStats", { attack: 2, health: 2, duration: "permanent" })])],
  p197: [ability("static", [effect("attachedConditionalStats", { attack: -2, health: 0, excludedNames: ["Recruta Exibido", "Recruta Iludido"], duration: "permanent" }), effect("keyword", { keyword: "Atropelar" })])],
  p198: [ability("activated", [effect("modifyStats", { target: "self", attack: 4, health: 4, duration: "combat" })], [{ type: "energy", amount: 1 }], { uiActivation: true, usageLimit: { count: 1, period: "turn" }, availability: { whileDefending: true } })],
  p200: [ability("static", [effect("enableChampionCombat")])],
  p201: [ability("static", [effect("faithfulSquireRedirect")])],
  p202: [ability("onPlay", [effect("heal", { amountPerTurnedCreature: 2, target: "controllerHero" })])],
  p203: [ability("onPlay", [effect("optionalSacrificeThenFillRecruits", { subtype: "Recruta", shuffle: true })])],
  p206: [ability("onPlay", [effect("buffFromSpellsThisTurn", { target: "anyCreature", selections: 1, attackPerSpell: 1, healthPerSpell: 1, duration: "turn" })])],
  p189: [ability("onEnter", [effect("heal", { amount: 2, target: "controllerHero" })])],
  p207: { ignored: true, reason: "removed-from-game" },
  p209: [ability("onPlay", [effect("purgeSpellsAndCreateImage", { name: "Tessália, a Mão de Ferro", oncePerGame: true })])],
  p210: [ability("onTargetedByOpponent", [effect("controllerChoice", { choices: [[effect("counterEvent")], [effect("damage", { amount: 4, target: "enemyHero" })]] })])],
  p211: { hero: true, evolution: [{ level: 2, condition: { catsInAllFieldsAtLeast: 5 } }, { level: 3, condition: { catsInAllFieldsAtLeast: 7 } }], levels: { 1: [ability("onSpellCast", [effect("addMarker", { target: "hero", marker: "coffee", amount: 1 }), effect("threshold", { marker: "coffee", amount: 10, reset: true, effects: [effect("createImage", { name: "Café Especial", destination: "hand" })] })], [], { condition: { spellNameIncludes: "Café" } })], 2: [ability("onPlayerDamaged", [effect("heal", { amount: 1, target: "controllerHero" })], [], { condition: { sourceSubtype: "Gato" } })], 3: [ability("static", [effect("allowSubtypeInZone", { subtype: "Gato", zone: "support", players: "both", countsAs: "Criatura", canAttachArtifact: false })])] } },
  p212: [ability("onMaintenance", [effect("createImage", { name: "Gato Multidimensional", destination: "activePlayerField", mandatory: true, replaceIfFull: true, supportAllowedIfHeroLevel: { hero: "Rasmus, o Barista do Tempo", level: 3 } })])],
  p213: [ability("static", [effect("cannotDefend"), effect("cannotBeDestroyedForSpace")]), ability("onEnter", [effect("loseLife", { amount: 1, target: "controllerHero" })]), ability("activated", [effect("moveSelf", { destination: "obscuro" })], [{ type: "energy", amount: 1 }], { uiActivation: true, usageLimit: { count: 1, period: "turn" } }), ability("onTurnEnd", [effect("loseLife", { amount: 1, target: "controllerHero" })], [], { condition: { controllerSubtypeEnteredThisTurn: { subtype: "Gato", count: 0 } } })],
  p214: [ability("static", [effect("dynamicCatStats")])],
  p217: [ability("onDestroyed", [effect("returnSelfToField")], [], { condition: { wasOnlySubtypeInAllFields: "Gato" } })],
  p219: [ability("static", [effect("costModifier", { selector: { controller: "self", zone: "hand" }, amount: -1, firstEachTurn: true })])],
  p221: [ability("onEnter", [effect("linkDestroyCreatures", { target: "anyCreature", selections: 1 })]), ability("onPermanentLeaves", [effect("destroyLinkedCreature")])],
  p225: [ability("onPlay", [effect("grantKeyword", { target: "anyPermanent", keyword: "Sufocado", duration: "turn" })])],
  p229: [ability("activated", [effect("createImage", { name: "Café Expresso", destination: "hand" })], [{ type: "tap", amount: 1 }], { usageLimit: { count: 1, period: "turn" } })],
  p230: [ability("onPlay", [effect("controllerChoice", { choices: [[effect("modifyStats", { attack: 1, health: 0, duration: "turn" })], [effect("modifyStats", { attack: 0, health: 1, duration: "turn" })]] })], [], { sourceText: "Escolha um efeito para a criatura alvo receber até o final do turno." })],
  p231: [ability("onPlay", [effect("controllerChoice", { choices: [[effect("createImagesAcrossFields", { name: "Gato Multidimensional", amount: 3 })], [effect("heal", { amount: 10, target: "controllerHero" })], [effect("draw", { amount: 3 })], [effect("levelHero", { amount: 1, maximum: 3 })]] })])],
  p233: [ability("static", [effect("cannotDefend"), effect("cannotBeDestroyedForSpace")]), ability("onEnter", [effect("loseLife", { amount: 1, target: "controllerHero" })]), ability("activated", [effect("moveSelf", { destination: "obscuro" })], [{ type: "energy", amount: 1 }], { uiActivation: true, usageLimit: { count: 1, period: "turn" } }), ability("onTurnEnd", [effect("loseLife", { amount: 1, target: "controllerHero" })], [], { condition: { controllerSubtypeEnteredThisTurn: { subtype: "Gato", count: 0 } } })],
  p234: [ability("onPlay", [effect("ready", { target: "anyCreature" }), effect("modifyStats", { target: "anyCreature", attack: 1, health: 1, duration: "turn" })])],
  p236: [ability("onPlay", [effect("grantDamageReductionShield", { target: "anyCreature", selections: 1, reduction: 1, uses: 1, duration: "turn" })])],
  p237: [ability("onPlay", [effect("grantDamageShield", { target: "anyCreature", uses: 1, duration: "untilUsed" })])],
  p238: [ability("onPlay", [effect("modifyStats", { target: "anyCreature", attack: 1, health: 1, duration: "untilNextTurn" }), effect("grantCombatImmobilize", { target: "anyCreature", duration: "untilNextTurn" })])],
  p241: [ability("onPlay", [effect("modifyStats", { target: "anyCreature", attack: 5, health: 5, duration: "untilNextTurn" }), effect("immobilize", { target: "anyCreature" })])],
  p243: [ability("onPlay", [effect("doubleNextNamedEffect", { controller: "self", nameIncludes: "Café", targetType: "Criatura", additionalTimes: 1 })])],
  p247: [ability("onNamedEffectApplied", [effect("copyEventEffect", { target: "self" })], [], { condition: { nameIncludes: "Café", eventTargetType: "Criatura" } })],
  p248: [ability("onPlay", [effect("repeatChoiceForCoffeeCount", { choices: [[effect("draw", { amount: 1 })], [effect("tap", { target: "anyCreature", selections: 1 })], [effect("modifyStats", { target: "anyCreature", attack: 2, health: 2, duration: "turn" })]] })])],
  p249: [ability("onPlay", [effect("modifyStats", { target: "anyCreature", attack: 5, health: 5, duration: "untilNextTurn" }), effect("immobilize", { target: "anyCreature" })])],
  p252: [ability("onPlay", [effect("increaseVitality", { amount: 2, target: "anyCharacter", duration: "permanent" })])],
  p255: { hero: true, evolution: [{ level: 2, condition: { heroMarkersAtLeast: 5, marker: "clue" } }, { level: 3, condition: { heroMarkersAtLeast: 10, marker: "clue" } }], levels: { 1: [ability("onInvestigate", [effect("addMarker", { target: "hero", marker: "clue", amount: 1 })]), ability("onMaintenance", [effect("chooseDeckAndInvestigate", { amount: 1 })], [], { condition: { eventOwnerIsController: true } })], 2: [ability("onInvestigate", [effect("optionalClueChoice", { cost: 2 })])], 3: [ability("activated", [effect("grantKeyword", { target: "allyCreature", keyword: "Furtivo", duration: "turn" })], [{ type: "removeHeroMarkers", marker: "clue", amount: 3 }], { uiActivation: true })] } },
  p256: [ability("onDestroyed", [effect("mill", { amount: 2, target: "enemy" })])],
  p257: [ability("onEnter", [effect("controllerChoice", { choices: [[effect("investigate", { amount: 2, target: "controllerDeck" })], [effect("investigate", { amount: 2, target: "opponentDeck" })]] })])],
  p261: [ability("onCardRevealed", [effect("modifyStats", { target: "self", attack: 1, health: 0, duration: "turn" })], [], { condition: { eventCardType: "Criatura" } })],
  p262: [ability("onCardRevealed", [effect("mill", { amount: 1, target: "enemy" })], [], { condition: { eventCardType: "Feitiço" } })],
  p263: [ability("onCardRevealed", [effect("damage", { amount: 1, target: "enemyCreature", selections: 1 })], [], { condition: { eventCardType: "Criatura" } }), ability("onCardRevealed", [effect("grantKeyword", { target: "self", keyword: "Barreira Mágica", duration: "turn" })], [], { condition: { eventCardType: "Feitiço" } }), ability("onCardRevealed", [effect("grantKeyword", { target: "self", keyword: "Furtivo", duration: "turn" })], [], { condition: { eventCardType: "Artefato" } })],
  p266: [ability("onPlay", [effect("archiveToGrave", { amount: 2 })])],
  p267: [ability("activated", [effect("gainEnergy", { amount: 1, destination: "main" })], [{ type: "tap", amount: 1 }], { uiActivation: true, availability: { controllerHasFaction: "Caos" } })],
  p268: [ability("static", [effect("keyword", { keyword: "Atropelar" })]), ability("onAttachedCreatureDamage", [effect("millFromDirectDamage")])],
  p272: [ability("onCardRevealed", [effect("mill", { amount: 1, target: "enemy" })], [], { condition: { eventCardType: "Criatura" } }), ability("onCardRevealed", [effect("damage", { amount: 1, target: "enemyCreature", selections: 1 })], [], { condition: { eventCardType: "Feitiço" } }), ability("onCardRevealed", [effect("gainEnergy", { amount: 1, destination: "reserve" })], [], { condition: { eventCardType: "Artefato" } }), ability("onCardRevealed", [effect("draw", { amount: 1 })], [], { condition: { eventCardType: "Encanto" } }), ability("onCardRevealed", [effect("discard", { amount: 1, target: "enemy" })], [], { condition: { eventCardType: "Terreno" } })],
  p273: { hero: true, evolution: [{ level: 2, condition: { vanillaConstantsAtLeast: 3 } }, { level: 3, condition: { vanillaConstantsAtLeast: 4 } }], levels: { 1: [ability("onCombatStart", [effect("modifyStats", { target: "anyCreature", vanillaOnly: true, attack: 1, health: 1, duration: "turn" })])], 2: [ability("static", [effect("vanillaDestructionReplacement")])], 3: [ability("static", [effect("grantKeyword", { target: "alliedCreatures", vanillaOnly: true, keyword: "Investida" })])] } },
  p265: [ability("onPlay", [effect("opponentChoice", { choices: [[effect("draw", { amount: 2, target: "controller" })], [effect("mill", { amount: 2, target: "chooser" })]] })])],
  p269: [ability("static", [effect("attachedStats", { attack: 2, health: 0 })]), ability("onAttachedCreatureDamage", [effect("loseLife", { amount: 1, target: "controllerHero" })])],
  p271: [ability("beforeDraw", [effect("optionalDrawFrom", { zonePosition: "bottom", fallback: "top" })])],
  p274: [ability("static", [effect("copyStrongestAllyStats", { target: "self", updateContinuously: true, bothStatsFromAttack: true })])],
  p280: [ability("onEnter", [effect("search", { zone: "deck", destination: "hand", types: ["Criatura"], vanillaOnly: true, amount: 1, shuffle: true })])],
  p283: [ability("static", [effect("cannotAttack")]), ability("onDamageTaken", [effect("becomeVanilla")], [], { condition: { eventSourceOwnerIsOpponent: true } })],
  p285: [ability("onPlay", [effect("grantKeyword", { target: "alliedCreatures", keyword: "Atropelar", duration: "turn" }), effect("controllerLifeThresholdStats", { target: "alliedCreatures", lifeAtMost: 10, attack: 2, health: 2, duration: "turn" })])],
  p286: [ability("onPlay", [effect("drawWithPenalty", { min: 0, max: 3, penaltyPerNonCreature: { amount: 3, target: "controllerHero" } })])],
  p287: [ability("onPlay", [effect("repeatDamageUntilDeaths", { amount: 1, targets: { perPlayer: 2, type: "Criatura" }, stopAfterDeaths: 2, simultaneousEachRound: true })])],
  p290: [ability("onMaintenance", [effect("draw", { amount: 1, target: "activePlayer" })], [], { condition: { activePlayerControlsVanillaCreature: true } })],
  p289: [ability("onPlay", [effect("search", { zone: "deck", destination: "hand", types: ["Criatura"], amount: 2, shuffle: true }), effect("moveCardsFromHandToDeckBottom", { amount: 2 })])],
  p291: { hero: true, evolution: [{ level: 2, condition: { totalMarkersAtLeast: 10 } }, { level: 3, condition: { totalMarkersAtLeast: 20 } }], levels: { 1: [ability("activated", [effect("addMarker", { target: "allyPermanent", marker: "action", amount: 2, selections: 2, maximumSelections: 2 })], [], { uiActivation: true, usageLimit: { count: 1, period: "turn" } })], 2: [ability("static", [effect("extraActionMarker")])], 3: [ability("activated", [effect("tap", { target: "anyCreature", selections: 1 })], [{ type: "removeMarkersFromConstants", amount: 4 }], { uiActivation: true })] } },
  p293: [ability("activated", [effect("search", { zone: "deck", destination: "hand", types: ["Artefato"], maxCostFromMarkerAmount: true, amount: 1, shuffle: true })], [{ type: "removeMarkers", marker: "action", amount: "X", minimum: 1 }], { uiActivation: true })],
  p295: [ability("onCreatureEnter", [effect("addMarker", { target: "self", marker: "action", amount: 1 })])],
  p296: [ability("static", [effect("keyword", { keyword: "Alerta" }), effect("attackPermission", { requiresMarkers: { marker: "action", minimum: 2 } })]), ability("onAttack", [effect("removeMarker", { target: "self", marker: "action", amount: 2 })])],
  p299: [ability("activated", [effect("drawPerMarkersRemoved", { marker: "action", divisor: 3 })], [{ type: "removeMarkers", marker: "action", amount: "X", multipleOf: 3, minimum: 3 }], { usageLimit: { count: 1, period: "turn" } })],
  p300: [ability("activated", [effect("search", { zone: "deck", types: ["Encanto", "Feitiço"], destination: "hand", shuffle: true })], [{ type: "removeMarkersFromConstants", amount: 5 }], { usageLimit: { count: 1, period: "turn" } })],
  p301: [ability("onEnter", [effect("doubleMarkers", { target: "allPermanents" }), effect("halveMaxEnergy", { target: "controller", rounding: "ceil" })])],
  p302: [ability("onAttachedCreatureTargeted", [effect("opponentChoice", { choices: [[effect("addMarker", { target: "attachedCreature", marker: "action", amount: 2 })], [effect("modifyStats", { target: "attachedCreature", attack: 1, health: 1, duration: "permanent" })]] })])],
  p303: [ability("onAttachedCreatureTargeted", [effect("optionalRedirect", { target: "anotherAllyPermanent", markerCost: 5 })])],
  p304: [ability("static", [effect("costModifier", { selector: { controller: "self", type: "Criatura", zone: "hand" }, amount: -1 })]), ability("onTurnEnd", [effect("loseLife", { amount: 1, target: "controllerHero" })])],
  p305: [ability("static", [effect("conditionalAttachedKeyword", { keyword: "Voar", requiresOtherFactionConstant: "Natureza" })])],
  p306: [ability("activated", [effect("gainMaxEnergy", { amount: 1 }), effect("destroy", { target: "self" })], [{ type: "tap", amount: 1 }], { uiActivation: true })],
  p309: [ability("onTurnEnd", [effect("consolidateMarkersAndDamage", { marker: "action", divisor: 3 })], [], { condition: { controllerOnlyCopyNamed: "ENCANTO 1" } }), ability("activated", [effect("moveMarker", { marker: "action", amount: 1, target: "anyPermanent", selections: 1 })], [{ type: "removeMarkers", marker: "action", amount: 2 }], { uiActivation: true })],
});

export const explicitRuleIds = Object.freeze(Object.keys(explicitCardRules));

export function getExplicitCardRule(cardOrId) {
  const id = typeof cardOrId === "string" ? cardOrId : cardOrId?.id;
  return id ? explicitCardRules[id] || null : null;
}

export function abilitiesForLevel(rule, level = 1) {
  if (!rule || Array.isArray(rule)) return rule || [];
  if (rule.ignored) return [];
  if (!rule.hero) return rule.abilities || [];
  return Object.entries(rule.levels || {}).flatMap(([required, abilities]) => Number(required) <= level ? abilities : []);
}
