from pathlib import Path

priority = Path('app/rules-engine/priority.mjs')
s = priority.read_text(encoding='utf-8')
old = '''export function chooseAIResponse(state, owner, random = Math.random) {\n  const legal = legalPriorityResponses(state, owner);'''
new = '''export function chooseAIResponse(state, owner, random = Math.random) {\n  const pending = state?.pendingResponse;\n  /* Once the opponent has passed, priority returns to the actor with passes=1.\n     The bot must pass here so the current top of the stack resolves instead of\n     extending its own chain with more responses indefinitely. */\n  if (pending?.responder === owner && pending?.actor === owner && (pending.passes || 0) > 0)\n    return { type: "passPriority", owner, auto: true };\n  const legal = legalPriorityResponses(state, owner);'''
if old not in s:
    raise SystemExit('chooseAIResponse anchor not found')
s = s.replace(old, new, 1)
priority.write_text(s, encoding='utf-8')

page = Path('app/page.tsx')
s = page.read_text(encoding='utf-8')
old = '''useEffect(()=>{const authoritativePending=game?.pendingResponse;if(authoritativePending?.responder!==1||mode!=="bot")return;const pendingKey=`${authoritativePending.actor}:${authoritativePending.responder}:${authoritativePending.passes??0}:${authoritativePending.action}`;const snapshot=currentGameRef.current;if(!snapshot||snapshot.winner!==null||snapshot.pendingResponse?.responder!==1)return;const delay=legalPriorityResponses(snapshot,1).length?420:50;const t=setTimeout(()=>{const current=currentGameRef.current;if(!current||current.winner!==null||mode!=="bot")return;const pending=current.pendingResponse;if(!pending||pending.responder!==1)return;const currentKey=`${pending.actor}:${pending.responder}:${pending.passes??0}:${pending.action}`;if(currentKey!==pendingKey)return;const command=chooseAIResponse(current,1,Math.random);const fallback=async()=>{await passPriorityWindow(1,true)};if(command.type==="passPriority"){void fallback();return}if(command.type==="activateHero"){void runRulesCommand(command,1).then(accepted=>{if(!accepted)void fallback()});return}const card=current.players[1].hand.find(c=>c.id===command.cardId),completed=card?completeAIPlayCommand(current,1,card,difficulty,{hasPriority:true}):null;if(!completed){void fallback();return}void runRulesCommand(completed,1).then(accepted=>{if(!accepted)void fallback()})},delay);return()=>clearTimeout(t)},[game?.pendingResponse?.actor,game?.pendingResponse?.responder,game?.pendingResponse?.passes,game?.pendingResponse?.action,mode,difficulty]);'''
new = '''useEffect(()=>{const authoritativePending=game?.pendingResponse;if(authoritativePending?.responder!==1||mode!=="bot")return;const pendingKey=`${authoritativePending.actor}:${authoritativePending.responder}:${authoritativePending.passes??0}:${authoritativePending.action}`;const snapshot=currentGameRef.current;if(!snapshot||snapshot.winner!==null||snapshot.pendingResponse?.responder!==1)return;const delay=(authoritativePending.passes??0)>0?40:legalPriorityResponses(snapshot,1).length?420:50;const act=()=>{const current=currentGameRef.current;if(!current||current.winner!==null||mode!=="bot")return;const pending=current.pendingResponse;if(!pending||pending.responder!==1)return;const currentKey=`${pending.actor}:${pending.responder}:${pending.passes??0}:${pending.action}`;if(currentKey!==pendingKey)return;const command=chooseAIResponse(current,1,Math.random);const fallback=async()=>{await passPriorityWindow(1,true)};if(command.type==="passPriority"){void fallback();return}if(command.type==="activateHero"){void runRulesCommand(command,1).then(accepted=>{if(!accepted)void fallback()});return}const card=current.players[1].hand.find(c=>c.id===command.cardId),completed=card?completeAIPlayCommand(current,1,card,difficulty,{hasPriority:true}):null;if(!completed){void fallback();return}void runRulesCommand(completed,1).then(accepted=>{if(!accepted)void fallback()})};const t=setTimeout(act,delay);/* Last-resort progress guard: if the exact same bot-owned priority window survives\n for far longer than a normal decision, force a pass instead of leaving the match locked. */const watchdog=setTimeout(()=>{const current=currentGameRef.current,pending=current?.pendingResponse;if(!current||pending?.responder!==1)return;const currentKey=`${pending.actor}:${pending.responder}:${pending.passes??0}:${pending.action}`;if(currentKey===pendingKey)void passPriorityWindow(1,true)},1600);return()=>{clearTimeout(t);clearTimeout(watchdog)}},[game?.pendingResponse?.actor,game?.pendingResponse?.responder,game?.pendingResponse?.passes,game?.pendingResponse?.action,mode,difficulty]);'''
if old not in s:
    raise SystemExit('AI priority effect anchor not found')
s = s.replace(old, new, 1)
page.write_text(s, encoding='utf-8')

css = Path('app/ui-overrides.css')
s = css.read_text(encoding='utf-8')
old = '.screen-game .game-content > .priority-stack-indicator{position:absolute!important;inset:auto!important;left:50%!important;top:50%!important;right:auto!important;bottom:auto!important;transform:translate(-50%,-50%)!important;'
new = '.screen-game .game-content > .priority-stack-indicator{position:absolute!important;inset:auto!important;left:50%!important;top:52.5%!important;right:auto!important;bottom:auto!important;transform:translate(-50%,-50%)!important;'
if old not in s:
    raise SystemExit('priority stack CSS anchor not found')
s = s.replace(old, new, 1)
css.write_text(s, encoding='utf-8')

Path('tests/ai-priority-progress.test.mjs').write_text('''import assert from "node:assert/strict";\nimport test from "node:test";\nimport fs from "node:fs";\nimport { chooseAIResponse } from "../app/rules-engine/priority.mjs";\n\ntest("AI passes when priority returns to the actor after the first pass",()=>{\n  const state={pendingResponse:{responder:1,actor:1,passes:1,action:"resposta da IA"},players:[{hand:[],board:[],support:[]},{hand:[{id:"fast",name:"Fast",type:"Feitiço",cost:0,tags:["Acelerado"],text:"Acelerado",abilities:[]}],board:[],support:[],heroId:"saymon",level:3,life:30,energy:10,reserve:3,abilityUses:{}}],active:1,round:3};\n  assert.deepEqual(chooseAIResponse(state,1,()=>0),{type:"passPriority",owner:1,auto:true});\n});\n\ntest("bot priority effect contains a stale-window watchdog",()=>{\n  const source=fs.readFileSync(new URL("../app/page.tsx",import.meta.url),"utf8");\n  assert.match(source,/Last-resort progress guard/);\n  assert.match(source,/setTimeout\(\(\)=>\{const current=currentGameRef\.current,pending=current\?\.pendingResponse/);\n});\n\ntest("stack indicator is slightly below geometric center",()=>{\n  const css=fs.readFileSync(new URL("../app/ui-overrides.css",import.meta.url),"utf8");\n  assert.match(css,/priority-stack-indicator\{[^}]*left:50%!important;top:52\.5%!important/s);\n});\n''', encoding='utf-8')
