from pathlib import Path

def rep(path, old, new):
 p=Path(path); t=p.read_text(encoding='utf-8')
 if old not in t: raise SystemExit(f'pattern missing: {path}: {old[:90]}')
 p.write_text(t.replace(old,new,1),encoding='utf-8')

rep('app/rules-engine/engine-base.mjs','if (condition.catsInAllFieldsAtLeast != null && state.players.flatMap((candidate) => candidate.board).filter((card) => subtype(card, "Gato")).length < condition.catsInAllFieldsAtLeast) return false;','if (condition.catsInAllFieldsAtLeast != null && state.players.flatMap((candidate) => permanentUnits(candidate)).filter((card) => subtype(card, "Gato")).length < condition.catsInAllFieldsAtLeast) return false;')
rep('app/rules-engine/card-rules.mjs','p245: [ability("static", [effect("dynamicSubtypeStats", { attackSubtype: "Gato", healthSubtype: "Cachorro" })])],','p245: [ability("static", [effect("dynamicSubtypeStats", { attackNameIncludes: "Gato", healthNameIncludes: "Cachorro" })])],')
rep('app/rules-engine/effects.mjs','dynamicSubtypeStats(state, effect, context) { const source = findUnit(state, context.sourceId); if (source) source.dynamicStats = { attackSubtype: effect.attackSubtype, healthSubtype: effect.healthSubtype }; },','dynamicSubtypeStats(state, effect, context) { const source = findUnit(state, context.sourceId); if (source) source.dynamicStats = { attackSubtype: effect.attackSubtype, healthSubtype: effect.healthSubtype, attackNameIncludes: effect.attackNameIncludes, healthNameIncludes: effect.healthNameIncludes }; },')
rep('app/rules-engine/engine-base.mjs','if (!unit?.suffocated && unit?.dynamicStats?.attackSubtype) return state.players.flatMap(permanentUnits).filter((card) => subtype(card, unit.dynamicStats.attackSubtype)).length;','if (!unit?.suffocated && unit?.dynamicStats?.attackNameIncludes) { const needle = String(unit.dynamicStats.attackNameIncludes).normalize("NFD").replace(/[\\u0300-\\u036f]/g, "").toLowerCase(); return (unit.atk || 0) + state.players.flatMap(permanentUnits).filter((card) => String(card.name || "").normalize("NFD").replace(/[\\u0300-\\u036f]/g, "").toLowerCase().includes(needle)).length; }\n  if (!unit?.suffocated && unit?.dynamicStats?.attackSubtype) return state.players.flatMap(permanentUnits).filter((card) => subtype(card, unit.dynamicStats.attackSubtype)).length;')
rep('app/rules-engine/engine-base.mjs','if (!unit?.suffocated && unit?.dynamicStats?.healthSubtype) return Math.max(1, state.players.flatMap(permanentUnits).filter((card) => subtype(card, unit.dynamicStats.healthSubtype)).length);','if (!unit?.suffocated && unit?.dynamicStats?.healthNameIncludes) { const needle = String(unit.dynamicStats.healthNameIncludes).normalize("NFD").replace(/[\\u0300-\\u036f]/g, "").toLowerCase(); return Math.max(1, (unit.hp || 1) + state.players.flatMap(permanentUnits).filter((card) => String(card.name || "").normalize("NFD").replace(/[\\u0300-\\u036f]/g, "").toLowerCase().includes(needle)).length); }\n  if (!unit?.suffocated && unit?.dynamicStats?.healthSubtype) return Math.max(1, state.players.flatMap(permanentUnits).filter((card) => subtype(card, unit.dynamicStats.healthSubtype)).length);')
rep('app/rules-engine/effects.mjs','linkDestroyCreatures(state, effect, context) { const source = findUnit(state, context.sourceId), target = findUnit(state, context.targetIds?.[0]); if (!source || !target || source === target) throw new RulesViolation("invalid-target"); source.linkedDestroyId = target.uid || target.id; target.linkedDestroyId = source.uid || source.id; },','linkDestroyCreatures(state, effect, context) { const source = findUnit(state, context.sourceId), target = findUnit(state, context.targetIds?.[0]); if (!source || !target || source === target) throw new RulesViolation("invalid-target"); const sourceId = source.uid || source.id, targetId = target.uid || target.id; source.linkedDestroyId = targetId; target.linkedDestroyId = sourceId; source.linkedCreatures = [sourceId, targetId]; target.linkedCreatures = [sourceId, targetId]; },')
rep('app/rules-engine/card-rules.mjs','p225: [ability("onPlay", [effect("grantKeyword", { target: "anyPermanent", keyword: "Sufocado", duration: "turn" })])],','p225: [ability("onPlay", [effect("suffocateUntilTurnEnd", { target: "anyPermanent", selections: 1 })])],')
old='  suffocateUntilTurnEndAndDrawOwner(state, effect, context) { const target = findUnit(state, context.targetIds?.[0]); if (!target) throw new RulesViolation("target-required"); target.suffocated = true; target.suffocatedUntilTurnEnd = true; const owner = state.players.findIndex((entry) => [...entry.board, ...entry.support, ...(entry.terrain ? [entry.terrain] : [])].includes(target)); defaultEffectHandlers.draw(state, { type: "draw", amount: 1 }, { ...context, owner }); },\n'
rep('app/rules-engine/effects.mjs',old,old+'  suffocateUntilTurnEnd(state, effect, context) { const target = findUnit(state, context.targetIds?.[0]); if (!target) throw new RulesViolation("target-required"); target.suffocated = true; target.suffocatedUntilTurnEnd = true; },\n')
rep('app/rules-engine/engine-base.mjs','"suffocateWhileSourceInField", "suffocateUntilTurnEndAndDrawOwner"','"suffocateWhileSourceInField", "suffocateUntilTurnEnd", "suffocateUntilTurnEndAndDrawOwner"')
rep('app/rules-engine/engine-base.mjs','unit.temporaryTags = []; unit.temporarySubtypes = []; unit.combatRestrictions = (unit.combatRestrictions || []).filter((rule) => rule.duration !== "turn");','unit.temporaryTags = []; unit.temporarySubtypes = []; if (unit.suffocatedUntilTurnEnd) { unit.suffocatedUntilTurnEnd = false; unit.suffocated = !!(unit.suffocatedBySources || []).length; } unit.combatRestrictions = (unit.combatRestrictions || []).filter((rule) => rule.duration !== "turn");')
rep('app/rules-engine/engine-base.mjs','else { const occupied = entry.board.find((unit) => unit.slot === command.slot); if ((occupied && entry.board.length < 5) || (!occupied && entry.board.length >= 5)) throw new RulesViolation("creature-zone-full"); }','else { const occupied = entry.board.find((unit) => unit.slot === command.slot); if (occupied?.cannotBeDestroyedForSpace) throw new RulesViolation("protected-space-occupant"); if ((occupied && entry.board.length < 5) || (!occupied && entry.board.length >= 5)) throw new RulesViolation("creature-zone-full"); }')
rep('app/rules-engine/engine-base.mjs','const replaced = entry.board.find((existing) => existing.slot === unit.slot); if ((replaced && entry.board.length < 5) || (!replaced && entry.board.length >= 5)) throw new RulesViolation("creature-zone-full"); if (replaced) {','const replaced = entry.board.find((existing) => existing.slot === unit.slot); if (replaced?.cannotBeDestroyedForSpace) throw new RulesViolation("protected-space-occupant"); if ((replaced && entry.board.length < 5) || (!replaced && entry.board.length >= 5)) throw new RulesViolation("creature-zone-full"); if (replaced) {')
