from pathlib import Path

page_path=Path('app/page.tsx')
page=page_path.read_text(encoding='utf-8')

old=''' function ResponseModal({action,available,budget,offTurn,seconds,passes=0,onPlay,onPass}:{action:string;available:Array<{card:CardDef;index:number;cost:number}>;budget:number;offTurn:boolean;seconds:number;passes?:number;onPlay:(idx:number)=>void;onPass:()=>void}){\n return <div className="overlay response-overlay"><section className="response-dialog" role="dialog" aria-modal="true" aria-labelledby="response-title"><header><span>JANELA DE RESPOSTA</span><b className={seconds<=5?"urgent":""}>⏱ {seconds}s</b><b>{offTurn?"Reserva":"Energia"} · {budget}</b></header><h2 id="response-title">Sua prioridade</h2><div className="priority-status"><b>{passes===0?"Primeiro passe":"Segundo passe"}</b><span>{passes===0?"A prioridade voltará ao jogador da ação.":"A ação será encerrada após este passe."}</span></div><p>O oponente realizou: <strong>{action}</strong>. Use um Feitiço Acelerado ou passe. A partida fica pausada até sua decisão.</p>{available.length?<div className="response-cards">{available.map(({card,index,cost})=><div key={`${card.id}-${index}`}><OriginalCard card={card} small inspectable={false} activeEffect="RESPOSTA ACELERADA" onClick={()=>onPlay(index)}/><b>{card.name}</b><small>Responder · custo {cost}</small></div>)}</div>:<div className="no-response-card"><i>◇</i><b>Nenhum Feitiço Acelerado utilizável</b><span>Não há cartas pagáveis com alvos válidos. Passe para devolver a prioridade.</span></div>}<footer><button className="pass-response" onClick={onPass}>Passar prioridade</button></footer></section></div>\n}'''
new=''' function ResponseModal({action,available,heroAbilities,budget,offTurn,seconds,passes=0,onPlay,onHeroAbility,onPass}:{action:string;available:Array<{card:CardDef;index:number;cost:number}>;heroAbilities:Array<{abilityId:string;label:string}>;budget:number;offTurn:boolean;seconds:number;passes?:number;onPlay:(idx:number)=>void;onHeroAbility:(abilityId:string)=>void;onPass:()=>void}){\n const hasResponses=available.length>0||heroAbilities.length>0;\n return <div className="overlay response-overlay"><section className="response-dialog" role="dialog" aria-modal="true" aria-labelledby="response-title"><header><span>JANELA DE RESPOSTA</span><b className={seconds<=5?"urgent":""}>⏱ {seconds}s</b><b>{offTurn?"Reserva":"Energia"} · {budget}</b></header><h2 id="response-title">Sua prioridade</h2><div className="priority-status"><b>{passes===0?"Primeiro passe":"Segundo passe"}</b><span>{passes===0?"A prioridade voltará ao jogador da ação.":"A ação será encerrada após este passe."}</span></div><p>O oponente realizou: <strong>{action}</strong>. Use um Feitiço Acelerado, uma habilidade ativa disponível do seu Herói ou passe.</p>{available.length?<div className="response-cards">{available.map(({card,index,cost})=><div key={`${card.id}-${index}`}><OriginalCard card={card} small inspectable={false} activeEffect="RESPOSTA ACELERADA" onClick={()=>onPlay(index)}/><b>{card.name}</b><small>Responder · custo {cost}</small></div>)}</div>:null}{heroAbilities.length?<div className="response-hero-abilities">{heroAbilities.map(ability=><button key={ability.abilityId} onClick={()=>onHeroAbility(ability.abilityId)}><i>⚡</i><span><b>{ability.label}</b><small>Habilidade ativa do Herói</small></span></button>)}</div>:null}{!hasResponses?<div className="no-response-card"><i>◇</i><b>Nenhuma resposta utilizável</b><span>Não há Feitiço Acelerado nem habilidade ativa de Herói legal neste momento. Passe para devolver a prioridade.</span></div>:null}<footer><button className="pass-response" onClick={onPass}>Passar prioridade</button></footer></section></div>\n}'''
if old not in page: raise SystemExit('ResponseModal block not found')
page=page.replace(old,new,1)

old=''' const hasUsableAcceleratedResponse=(state:Game,owner:0|1=0)=>{const player=state.players[owner],budget=responseBudget(state,owner);return player.hand.some(card=>{if(!isFast(card)||effectiveCost(card,player)>budget)return false;const policy=playTargetPolicy(card);return policy.selections<=0||canChooseAllTargets(card,policy.steps||[])})};\n const usableAcceleratedResponses=(state:Game,owner:0|1=0)=>{const player=state.players[owner],budget=responseBudget(state,owner);return player.hand.map((card,index)=>({card,index,cost:effectiveCost(card,player)})).filter(({card,cost})=>{if(!isFast(card)||cost>budget)return false;const policy=playTargetPolicy(card);return policy.selections<=0||canChooseAllTargets(card,policy.steps||[])})};\n useEffect(()=>{if(!game||responseWindow?.responder!==0||priorityControl!=="assisted")return;if(hasUsableAcceleratedResponse(game,0))return;const t=setTimeout(()=>{void passPriorityWindow(0,true);if(mode==="bot")update(g=>log(g,"Sem Acelerado utilizável — prioridade passada automaticamente.","response"))},80);return()=>clearTimeout(t)},[game,responseWindow,mode,priorityControl]);'''
new=''' const hasUsableAcceleratedResponse=(state:Game,owner:0|1=0)=>{const player=state.players[owner],budget=responseBudget(state,owner);return player.hand.some(card=>{if(!isFast(card)||effectiveCost(card,player)>budget)return false;const policy=playTargetPolicy(card);return policy.selections<=0||canChooseAllTargets(card,policy.steps||[])})};\n const usableAcceleratedResponses=(state:Game,owner:0|1=0)=>{const player=state.players[owner],budget=responseBudget(state,owner);return player.hand.map((card,index)=>({card,index,cost:effectiveCost(card,player)})).filter(({card,cost})=>{if(!isFast(card)||cost>budget)return false;const policy=playTargetPolicy(card);return policy.selections<=0||canChooseAllTargets(card,policy.steps||[])})};\n const heroPriorityResponses=(state:Game,owner:0|1=0)=>legalPriorityResponses(state,owner).filter((command:any)=>command.type==="activateHero").map((command:any)=>{const slot=command.abilityId==="saymon-level-1"?0:command.abilityId==="saymon-level-2"?1:command.abilityId==="ngoro-level-2"?1:command.abilityId==="ngoro-level-3"?2:command.abilityId==="natureza-level-1"?0:command.abilityId==="natureza-level-3"?2:-1;return{abilityId:command.abilityId,label:slot>=0?deckById(state.players[owner].heroId).abilities[slot]:command.label||"Habilidade do Herói"}});\n const hasUsablePriorityResponse=(state:Game,owner:0|1=0)=>hasUsableAcceleratedResponse(state,owner)||heroPriorityResponses(state,owner).length>0;\n useEffect(()=>{if(!game||responseWindow?.responder!==0||priorityControl!=="assisted")return;if(hasUsablePriorityResponse(game,0))return;const t=setTimeout(()=>{void passPriorityWindow(0,true);if(mode==="bot")update(g=>log(g,"Sem resposta utilizável — prioridade passada automaticamente.","response"))},80);return()=>clearTimeout(t)},[game,responseWindow,mode,priorityControl]);'''
if old not in page: raise SystemExit('priority UI helper block not found')
page=page.replace(old,new,1)

old=''' const declineResponse=()=>{void passPriorityWindow(0)};'''
new=''' const chooseHeroResponse=(abilityId:string)=>{if(!game)return;const command=legalPriorityResponses(game,0).find((candidate:any)=>candidate.type==="activateHero"&&candidate.abilityId===abilityId);if(command)void runRulesCommand(command,0)};\n const declineResponse=()=>{void passPriorityWindow(0)};'''
if old not in page: raise SystemExit('declineResponse anchor not found')
page=page.replace(old,new,1)

old='''{responseWindow?.responder===0&&(priorityControl==="full-control"||hasUsableAcceleratedResponse(game,0))&&<ResponseModal action={responseWindow.action} available={usableAcceleratedResponses(game,0)} budget={responseBudget(game,0)} offTurn={game.active!==0} seconds={responseRemaining} passes={responseWindow.passes??0} onPlay={chooseResponse} onPass={declineResponse}/>}'''
new='''{responseWindow?.responder===0&&(priorityControl==="full-control"||hasUsablePriorityResponse(game,0))&&<ResponseModal action={responseWindow.action} available={usableAcceleratedResponses(game,0)} heroAbilities={heroPriorityResponses(game,0)} budget={responseBudget(game,0)} offTurn={game.active!==0} seconds={responseRemaining} passes={responseWindow.passes??0} onPlay={chooseResponse} onHeroAbility={chooseHeroResponse} onPass={declineResponse}/>}'''
if old not in page: raise SystemExit('ResponseModal render anchor not found')
page=page.replace(old,new,1)
page_path.write_text(page,encoding='utf-8')

css_path=Path('app/ui-overrides.css')
css=css_path.read_text(encoding='utf-8')
css+='''\n/* Hero abilities inside priority response windows. */\n.screen-game .response-hero-abilities{display:flex;flex-direction:column;gap:clamp(.3rem,.55cqh,.55rem);padding:0 clamp(.65rem,1.15cqw,1rem) clamp(.55rem,1cqh,.9rem)}\n.screen-game .response-hero-abilities>button{display:grid;grid-template-columns:clamp(1.5rem,2.25cqw,2rem) minmax(0,1fr);align-items:center;gap:clamp(.35rem,.65cqw,.6rem);width:100%;padding:clamp(.42rem,.72cqh,.65rem) clamp(.5rem,.85cqw,.75rem);border:1px solid rgb(100 205 255/.58);border-radius:clamp(.3rem,.5cqw,.48rem);background:linear-gradient(135deg,rgb(21 79 126/.78),rgb(7 25 42/.96));color:#eaf8ff;text-align:left;box-shadow:0 0 clamp(.25rem,.55cqw,.5rem) rgb(65 170 255/.18)}\n.screen-game .response-hero-abilities>button:hover{border-color:rgb(149 227 255/.92);box-shadow:0 0 clamp(.4rem,.8cqw,.75rem) rgb(65 170 255/.38)}\n.screen-game .response-hero-abilities i{display:grid;place-items:center;aspect-ratio:1;border:1px solid rgb(145 225 255/.68);border-radius:50%;font-style:normal;color:#9fe5ff}\n.screen-game .response-hero-abilities span{min-width:0;display:flex;flex-direction:column;gap:.12rem}\n.screen-game .response-hero-abilities b{font-size:clamp(.46rem,.72cqw,.68rem);line-height:1.2}\n.screen-game .response-hero-abilities small{color:#91b9ce;font-size:clamp(.38rem,.56cqw,.52rem)}\n'''
css_path.write_text(css,encoding='utf-8')

Path('tests/hero-priority-ui.test.mjs').write_text('''import assert from "node:assert/strict";\nimport test from "node:test";\nimport { readFile } from "node:fs/promises";\n\ntest("human priority UI exposes hero abilities and assisted mode does not auto-pass them",async()=>{\n const page=await readFile(new URL("../app/page.tsx",import.meta.url),"utf8");\n assert.match(page,/heroPriorityResponses/);\n assert.match(page,/hasUsablePriorityResponse/);\n assert.match(page,/onHeroAbility=\\{chooseHeroResponse\\}/);\n assert.match(page,/Habilidade ativa do Herói/);\n assert.doesNotMatch(page,/priorityControl==="full-control"\\|\\|hasUsableAcceleratedResponse\\(game,0\\)/);\n});\n''',encoding='utf-8')
