from pathlib import Path

priority_path = Path('app/rules-engine/priority.mjs')
priority = priority_path.read_text(encoding='utf-8')
priority = priority.replace('import { canExecuteCard, validateCosts } from "./engine.mjs";\n', 'import { canExecuteCard, validateCosts } from "./engine.mjs";\nimport { abilitiesForLevel, getExplicitCardRule } from "./card-rules.mjs";\n')
priority = priority.replace('const permanents = (player) => [...(player.board || []), ...(player.support || []), ...(player.terrain ? [player.terrain] : [])];\n', 'const permanents = (player) => [...(player.board || []), ...(player.support || []), ...(player.terrain ? [player.terrain] : [])];\nconst HERO_RULE_PAGE = Object.freeze({ saymon: 129, ngoro: 255, natureza: 291 });\nconst heroSource = (entry, owner) => ({ uid: `${entry.heroId}-hero-${owner}`, id: `${entry.heroId}-hero-${owner}`, name: entry.heroId, slot: -1 });\nconst stackHas = (state, predicate) => (state.priorityStack || []).some((frame) => frame?.kind === "command" && predicate(frame.command || {}));\nconst heroUsageKey = (state, source, ability) => `${source.uid || source.id}:${ability.id}${ability?.condition?.firstEachTurn ? `:round-${state.round}` : ""}`;\n')
old = '  const cards = player.hand.flatMap((card, handIndex) => isAccelerated(card) && canExecuteCard(card) && responseEnergy >= spellCost(state, owner, card)\n    ? [{ type: "playCard", owner, cardId: card.id, handIndex, hasPriority: true, label: card.name || card.id }]\n    : []);\n  // Response windows are intentionally limited to Accelerated cards.\n  // Activated permanent abilities are main-phase actions and must never keep\n  // an AI priority window alive.\n  return cards;'
new = '  const cards = player.hand.flatMap((card, handIndex) => isAccelerated(card) && canExecuteCard(card) && responseEnergy >= spellCost(state, owner, card) && !stackHas(state, command => command.type === "playCard" && command.owner === owner && command.cardId === card.id)\n    ? [{ type: "playCard", owner, cardId: card.id, handIndex, hasPriority: true, label: card.name || card.id }]\n    : []);\n  const page = HERO_RULE_PAGE[player.heroId];\n  const rule = page ? getExplicitCardRule(`p${page}`) : null;\n  const source = heroSource(player, owner);\n  const heroAbilities = abilitiesForLevel(rule, player.level || 1).flatMap((ability) => {\n    if (ability.trigger !== "activated" || ability.responseAllowed === false || !ability.id) return [];\n    if (player.abilityUses?.[heroUsageKey(state, source, ability)]) return [];\n    if (stackHas(state, command => command.type === "activateHero" && command.owner === owner && command.abilityId === ability.id)) return [];\n    try { validateCosts(state, ability, { owner, sourceId: source.uid }); } catch { return []; }\n    return [{ type: "activateHero", owner, abilityId: ability.id, hasPriority: true, label: `${player.heroId}: ${ability.id}` }];\n  });\n  return [...cards, ...heroAbilities];'
if old not in priority:
    raise SystemExit('priority response block not found')
priority_path.write_text(priority.replace(old, new, 1), encoding='utf-8')

engine_path = Path('app/rules-engine/engine.mjs')
engine = engine_path.read_text(encoding='utf-8')
anchor = '  if (priorityEnabled && command.type === "passPriority" && (inputState.priorityStack?.length || 0) > 1) {'
hero_block = '  if (priorityEnabled && command.type === "activateHero" && command.hasPriority && !command.skipPriority && inputState.pendingResponse) {\n    if (inputState.pendingResponse.responder !== command.owner) throw new RulesViolation("not-your-priority");\n    const existingStack = inputState.priorityStack || [];\n    if (existingStack.some((frame) => frame.kind === "command" && frame.command?.type === "activateHero" && frame.command?.owner === command.owner && frame.command?.abilityId === command.abilityId)) throw new RulesViolation("hero-response-already-on-stack");\n    const root = existingStack.length ? null : rootPriorityFrame(inputState);\n    if (!existingStack.length && !root) throw new RulesViolation("nothing-to-respond-to");\n    const state = clone(inputState);\n    state.priorityStack = existingStack.length ? clone(existingStack) : [root];\n    state.priorityStack.push(commandFrame(inputState, command));\n    state.pendingResponse = { responder: 1 - command.owner, actor: command.owner, action: command.abilityId || "habilidade de herói", passes: 0 };\n    return stackResult(state, ["priority:push-hero-ability"], 0);\n  }\n\n'
if hero_block not in engine:
    if anchor not in engine:
        raise SystemExit('engine pass priority anchor not found')
    engine = engine.replace(anchor, hero_block + anchor, 1)
engine_path.write_text(engine, encoding='utf-8')

base_path = Path('app/rules-engine/engine-base.mjs')
base = base_path.read_text(encoding='utf-8')
old_guard = '        if (state.active !== item.command.owner || state.phase !== "principal") throw new RulesViolation("not-your-turn");'
new_guard = '        const priorityHeroActivation = !!item.command.hasPriority;\n        if (!priorityHeroActivation && (state.active !== item.command.owner || state.phase !== "principal")) throw new RulesViolation("not-your-turn");'
if old_guard not in base:
    raise SystemExit('activateHero turn guard not found')
base_path.write_text(base.replace(old_guard, new_guard, 1), encoding='utf-8')

page_path = Path('app/page.tsx')
page = page_path.read_text(encoding='utf-8')
old_ai = 'if(command.type==="passPriority"){void fallback();return}const card=current.players[1].hand.find(c=>c.id===command.cardId),completed=card?completeAIPlayCommand(current,1,card,difficulty,{hasPriority:true}):null;if(!completed){void fallback();return}void runRulesCommand(completed,1).then(accepted=>{if(!accepted)void fallback()})'
new_ai = 'if(command.type==="passPriority"){void fallback();return}if(command.type==="activateHero"){void runRulesCommand(command,1).then(accepted=>{if(!accepted)void fallback()});return}const card=current.players[1].hand.find(c=>c.id===command.cardId),completed=card?completeAIPlayCommand(current,1,card,difficulty,{hasPriority:true}):null;if(!completed){void fallback();return}void runRulesCommand(completed,1).then(accepted=>{if(!accepted)void fallback()})'
if old_ai not in page:
    raise SystemExit('AI priority command branch not found')
page_path.write_text(page.replace(old_ai, new_ai, 1), encoding='utf-8')

Path('tests/hero-priority-response.test.mjs').write_text('''import assert from "node:assert/strict";\nimport test from "node:test";\nimport { legalPriorityResponses, chooseAIResponse } from "../app/rules-engine/priority.mjs";\nimport { executeCommand } from "../app/rules-engine/engine.mjs";\n\nconst player=(heroId, level, extra={})=>({heroId,level,life:20,energy:3,reserve:3,hand:[],board:[],support:[],terrain:null,abilityUses:{},markers:{clue:10},heroXP:10,...extra});\nconst baseState=()=>({active:0,phase:"combate",round:4,pendingAction:{type:"attack",owner:0},pendingResponse:{responder:1,actor:0,action:"ataque",passes:0},players:[player("saymon",3),player("saymon",3)]});\n\ntest("activated hero abilities are legal priority responses even off turn",()=>{\n  const state=baseState();\n  const legal=legalPriorityResponses(state,1);\n  assert.ok(legal.some(command=>command.type==="activateHero"&&command.abilityId==="saymon-level-1"));\n  assert.equal(chooseAIResponse(state,1,()=>0).type,"activateHero");\n});\n\ntest("hero priority response is stacked and cannot be offered twice before resolution",()=>{\n  const state=baseState();\n  const command=legalPriorityResponses(state,1).find(item=>item.type==="activateHero"&&item.abilityId==="saymon-level-1");\n  const stacked=executeCommand(state,command,{priority:true}).state;\n  assert.equal(stacked.priorityStack.at(-1).command.type,"activateHero");\n  assert.equal(stacked.pendingResponse.responder,0);\n  const pretendTurnBack={...stacked,pendingResponse:{...stacked.pendingResponse,responder:1}};\n  assert.ok(!legalPriorityResponses(pretendTurnBack,1).some(item=>item.type==="activateHero"&&item.abilityId==="saymon-level-1"));\n});\n\ntest("hero response reaches its target decision after both players pass",()=>{\n  let state=baseState();\n  const command=legalPriorityResponses(state,1).find(item=>item.type==="activateHero"&&item.abilityId==="saymon-level-1");\n  state=executeCommand(state,command,{priority:true}).state;\n  state=executeCommand(state,{type:"passPriority",owner:0},{priority:true}).state;\n  assert.equal(state.pendingResponse.responder,1);\n  state=executeCommand(state,{type:"passPriority",owner:1},{priority:true}).state;\n  assert.equal(state.pendingDecision?.owner,1);\n  assert.equal(state.pendingDecision?.kind,"activation-targets");\n});\n''', encoding='utf-8')
