import assert from "node:assert/strict";
import test from "node:test";
import cards from "../app/cards.generated.json" with { type: "json" };
import { compileCard } from "../app/rules-engine/compiler.mjs";
import { executeCommand } from "../app/rules-engine/engine.mjs";
import { getExplicitCardRule } from "../app/rules-engine/card-rules.mjs";

const catalog = cards.map(compileCard);
const state = (level = 1) => ({ active:0, phase:"principal", round:1, cardCatalog:catalog, players:[0,1].map((owner)=>({heroId:owner?"gimble":"quarion",level:owner?1:level,heroXP:0,levelUpsThisTurn:0,markers:{},abilityUses:{},life:30,maxLife:30,energy:20,maxEnergy:10,reserve:3,deck:[],extraDeck:[],hand:[],board:[],support:[],terrain:null,grave:[],obscuro:[],turnCardsPlayed:0,turnSpellsPlayed:0})) });
const printed = (page, overrides={}) => ({...compileCard(cards.find((card)=>card.page===page)),...overrides});
const unit = (id,overrides={}) => ({uid:id,id,name:id,type:"Criatura",cost:1,atk:1,hp:4,text:"",tags:[],subtypes:[],abilities:[],slot:0,damage:0,modifiers:[],exhausted:false,summoning:false,...overrides});

test("removed Quarion cards are absent from canonical catalog",()=>{for(const page of [200,201,203,204,205,207,209,210])assert.equal(cards.some((card)=>card.page===page),false,`page ${page}`)});
test("Quarion evolution rule counts distinct creature names regardless of First Act",()=>{const rule=getExplicitCardRule("p180");assert.equal(rule.evolution[0].condition.distinctCreatureNamesAtLeast,2);assert.equal(rule.evolution[1].condition.distinctCreatureNamesAtLeast,4);assert.equal("distinctFirstActNamesAtLeast" in rule.evolution[0].condition,false)});
test("Recruta Bom de Briga has explicit 2 damage First Act",()=>{const rule=getExplicitCardRule("p187");assert.equal(rule[0].trigger,"onEnter");assert.deepEqual(rule[0].effects[0],{type:"damage",amount:2,target:"anyCreature",selections:1})});
test("Caneca makes spell damage zero but does not prevent creature effect damage",()=>{let game=state();const host={...printed(189),uid:"ping",slot:0,hp:10,damage:0,modifiers:[],staticModifiers:[],exhausted:false,summoning:false};const mug={...printed(192),uid:"mug",slot:0,attachedTo:"ping",enteredRound:0,damage:0,modifiers:[],staticModifiers:[],exhausted:false,summoning:false};game.players[0].board.push(host);game.players[0].support.push(mug);game=executeCommand(game,{type:"emit",owner:0,event:{type:"noop",owner:0}}).state;game.active=1;game.players[1].hand.push({id:"spell",name:"Spell",type:"Feitiço",cost:0,tags:[],abilities:[{id:"spell-hit",trigger:"onPlay",costs:[],effects:[{type:"damage",amount:3,target:"anyCreature",selections:1}]}]});game=executeCommand(game,{type:"playCard",owner:1,cardId:"spell",targetIds:["ping"],skipPriority:true}).state;assert.equal(game.players[0].board.find((card)=>card.uid==="ping").damage,0);game.players[1].hand.push(unit("creature-effect",{abilities:[{id:"ping",trigger:"onEnter",costs:[],effects:[{type:"damage",amount:1,target:"anyCreature",selections:1}]}]}));game=executeCommand(game,{type:"playCard",owner:1,cardId:"creature-effect",slot:0,targetIds:["ping"],skipPriority:true}).state;assert.equal(game.players[0].board.find((card)=>card.uid==="ping").damage,1)});
test("Chefe doubles a triggered effect from a Recruit",()=>{const game=state();game.players[0].board.push(unit("chief",{page:182,slot:0,subtypes:["Recruta"],staticModifiers:[{type:"doubleRecruitEffects"}]}),unit("recruit",{slot:1,subtypes:["Recruta"],abilities:[{id:"hurt-draw",trigger:"onDamageTaken",costs:[],effects:[{type:"draw",amount:1}]}]}));game.players[0].deck.push({id:"a"},{id:"b"},{id:"c"});const result=executeCommand(game,{type:"emit",owner:0,event:{type:"onDamageTaken",owner:0,targetId:"recruit",amount:1}}).state;assert.equal(result.players[0].hand.length,2)});
test("Chefe does not double an attached artifact effect",()=>{const game=state();game.players[0].board.push(unit("chief",{page:182,slot:0,subtypes:["Recruta"],staticModifiers:[{type:"doubleRecruitEffects"}]}),unit("recruit",{slot:1,subtypes:["Recruta"]}));game.players[0].support.push({uid:"artifact",id:"artifact",name:"Artifact",page:999,type:"Artefato",slot:1,attachedTo:"recruit",suffocated:false,abilities:[{id:"artifact-draw",trigger:"onAttachedCreatureTargeted",costs:[],effects:[{type:"draw",amount:1}]}],staticModifiers:[]});game.players[0].deck.push({id:"a"},{id:"b"});const result=executeCommand(game,{type:"emit",owner:0,event:{type:"onAttachedCreatureTargeted",owner:1,sourceId:"enemy",targetIds:["recruit"]}}).state;assert.equal(result.players[0].hand.length,1)});
for(const destination of ["hand","obscuro","grave"])test(`Saideira replays First Act on leave to ${destination}`,()=>{const game=state();game.players[0].terrain={uid:"saideira",id:"saideira",name:"Saideira",page:181,type:"Terreno",slot:0,suffocated:false,staticModifiers:[{type:"recruitFirstActOnLeave"}],abilities:[]};const recruit=unit("leaver",{subtypes:["Recruta"],tags:["Primeiro Ato"],abilities:[{id:"first",trigger:"onEnter",costs:[],effects:[{type:"draw",amount:1}]}]});game.players[0].deck.push({id:"draw"});const result=executeCommand(game,{type:"emit",owner:0,event:{type:"onPermanentLeaves",owner:0,sourceId:"leaver",card:recruit,zone:"board",destination}}).state;assert.equal(result.players[0].hand.length,1)});
test("Saideira replay is doubled by Chefe without looping",()=>{const game=state(3);game.players[0].terrain={uid:"saideira",id:"saideira",name:"Saideira",page:181,type:"Terreno",slot:0,suffocated:false,staticModifiers:[{type:"recruitFirstActOnLeave"}],abilities:[]};game.players[0].board.push(unit("chief",{page:182,slot:0,subtypes:["Recruta"],staticModifiers:[{type:"doubleRecruitEffects"}]}));const recruit=unit("leaver",{slot:1,subtypes:["Recruta"],tags:["Primeiro Ato"],abilities:[{id:"first",trigger:"onEnter",costs:[],effects:[{type:"draw",amount:1}]}]});game.players[0].deck.push({id:"a"},{id:"b"},{id:"c"});const result=executeCommand(game,{type:"emit",owner:0,event:{type:"onPermanentLeaves",owner:0,sourceId:"leaver",card:recruit,zone:"board",destination:"hand"}}).state;assert.equal(result.players[0].hand.length,2)});
