"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import rawCards from "./cards.generated.json";
import { RemoteCardArt } from "./remote-card-art";
import { canActivateCard, hasActivatableEffect } from "./card-activation.mjs";
import { compileCard } from "./rules-engine/compiler.mjs";
import { canExecuteCard, executeCommand } from "./rules-engine/engine.mjs";
import { chooseAIResponse, legalPriorityResponses, shouldAutoPass } from "./rules-engine/priority.mjs";
import { aiDifficultyProfile, canAIPlayLifeCost, chooseAIPlayable, orderAIAttackers, preferredAISlot } from "./rules-engine/ai.mjs";
import { hasSubtype } from "./rules-engine/subtypes.mjs";
import { cardPlayTargetPolicy, isValidTarget, targetPolicy, TargetScope } from "./rules-engine/targeting.mjs";
import { applyCloneRetaliation, claimOncePerTurn, earthquakeDamage, elementalChainFrom as ruleElementalChainFrom } from "./game-rules.mjs";

type CardType="Criatura"|"Feitiço"|"Artefato"|"Encanto"|"Terreno"|"Herói";
type CardDef={page:number;id:string;name:string;type:CardType;cost:number;atk?:number;hp?:number;text:string;tags:string[];image:string;hero:boolean;imageCard:boolean;revealed?:boolean;subtypes?:string[];abilities?:any[];rules?:unknown;diagnostics?:{source?:string;unsupported?:number};generatedImage?:boolean};
const immediateCardEffectText=(card:CardDef)=>card.text.split(/neste turno,\s*seu próximo/i)[0];
const cardPlayEffectText=(card:CardDef)=>card.type!=="Criatura"?immediateCardEffectText(card):card.text.match(/primeiro ato\s*:\s*([\s\S]*?)(?=(?:último suspiro|fura-fila)\s*:|$)/i)?.[1]?.trim()||"";
type Unit=CardDef&{uid:string;slot:number;enteredRound?:number;damage:number;bonusAtk:number;bonusHp:number;temporaryAtk?:number;temporaryHp?:number;temporaryTags?:string[];temporarySubtypes?:string[];combatRestrictions?:Array<{cannotCombatSubtype?:string;duration?:string}>;attackLimit?:number;attacksThisTurn?:number;markers:number;modifiers?:Array<{attack?:number;health?:number;duration?:string;sourceId?:string}>;grantedKeywords?:string[];staticModifiers?:any[];lastDamagedBy?:string;damagedOwnersThisTurn?:number[];activatedThisTurn?:boolean;attackedThisTurn?:boolean;exhausted:boolean;summoning:boolean;frozen:boolean;stunned:boolean;suffocated:boolean;immobilized:boolean;impacting?:boolean;defenseUses:number;attachedTo?:string;temporary?:boolean;generatedImage?:boolean};
type ElementName="Fogo"|"Água"|"Terra"|"Ar";
type Player={heroId:string;level:number;heroXP:number;levelUpsThisTurn:number;life:number;lifeLostThisTurn?:number;lifeLossEvents?:number;maxEnergy:number;energy:number;reserve:number;noReserveStorageThisTurn?:boolean;nextCardDiscounts?:Array<{amount:number;type?:CardType;typeNot?:CardType;expiresRound?:number}>;deck:CardDef[];extraDeck:CardDef[];hand:CardDef[];board:Unit[];support:Unit[];terrain:Unit|null;grave:CardDef[];obscuro:CardDef[];cardsPlayed:number;turnCardsPlayed:number;goblinTurnCardsPlayed?:number;turnSpellsPlayed:number;spellsPlayed:number;coffeeSpells:number;damageDealt:number;turnDeaths:number;abilityUses:Record<string,number>;pendingTranqueira:boolean;nextCardDiscount:number;nextNonCreatureDiscount:number;nextSpellDiscount:number;nextSummonPaysLife:boolean;nextCreaturePaysLife?:boolean;catsEnteredThisTurn:number;elementChain?:{element:ElementName;effect:"Sufocado"|"Atordoado"|"Congelado"|"Imobilizado"};nextElementEffects?:Array<{element:ElementName;keyword:string;expires?:string}>;lastElement?:ElementName;lastElementSource?:string};
type Phase="manutencao"|"principal"|"combate"|"fim";
/* Heroes are valid targets only for explicit damage or healing effects. */
const allowsHeroTarget=(card:CardDef|undefined,step=0)=>!!card&&(targetPolicy({...card,text:cardPlayEffectText(card)}).steps?.[step]?.scope??targetPolicy({...card,text:cardPlayEffectText(card)}).scope)===TargetScope.ANY_CHARACTER;
type Game={players:[Player,Player];active:0|1;phase:Phase;round:number;log:{id:string;text:string;tone?:string}[];winner:number|null;selectedAttackers:string[];events:number;combatAction?:CombatAction|null;pendingAction?:Record<string,unknown>;priorityStack?:Array<{kind?:string;actor?:0|1;label?:string;command?:Record<string,unknown>}>;pendingResponse?:PendingResponse|null;pendingDecision?:PendingDecision|null;pendingReposition?:{owners:Array<0|1>;confirmed:Array<0|1>;activeOwner?:0|1;moveAttachments:boolean;sourceId?:string;deadline?:number}|null;turnDeadline?:number|null};
type Screen="menu"|"setup"|"decks"|"game";
type Targeting={kind:"attach"|"spell"|"gimble"|"natureza"|"saymon"|"saymon-life"|"ngoro"|"uruk-fire";source:string;cardIndex?:number;amount?:number;response?:boolean;fieldSlot?:number;required?:number;selected?:string[]};
type ImageChoice={cardIndex:number;cardName:string;options:string[]};
type CafeChoice="cats"|"heal"|"draw"|"level";
type PendingResponse={responder:0|1;actor:0|1;action:string;deadline?:number;passes?:number};
type PendingDecision={kind:string;owner:0|1;effect:{choices?:any[][];replayEffects?:any[];maximum?:number;amount?:number;types?:string[];subtype?:string;vanillaOnly?:boolean;minCost?:number;maxCost?:number;maxCostFromMarkerAmount?:boolean;markerCost?:number};context?:Record<string,any>;targetSteps?:Array<{scope:string;role?:string;requiredSubtype?:string;requiredName?:string;imageOnly?:boolean;excludeIds?:string[];maxCost?:number;requireExhausted?:boolean;requiresDamagedOwnerThisTurn?:boolean}>;sourceName?:string};
type MatchSettings={startingLife:number;responseSeconds:number;turnSeconds:number};
type CombatStage="declared"|"priority"|"choosing"|"charging"|"impact"|"resolved";
type CombatAction={attackerOwner:0|1;attackerUid:string;attackerCard:CardDef;defenderUid?:string;defenderCard?:CardDef;targetHero?:boolean;stage:CombatStage;result?:string;destroyed?:Array<"attacker"|"defender">;winnerText?:string;attackDamage?:number;counterDamage?:number};
type VisualFx={id:string;kind:"summon"|"spell"|"artifact"|"terrain"|"ability"|"damage";theme:"blood"|"dragon"|"goblin"|"recruit"|"divine"|"nature"|"arcane"|"chaos"|"order"|"neutral";card?:CardDef;target?:CardDef;label:string;detail:string};
const VISUAL_FX_HOLD_MS=2280;
const COMBAT_STAGE_DELAY_MS:Record<CombatStage,number>={declared:220,priority:180,choosing:0,charging:320,impact:550,resolved:450};
const RESPONSE_REVEAL_DELAY_MS=2200;
type SearchRequest={id:string;owner:0|1;sourceName:string;sourcePage:number;text:string;limit:number;filterLabel:string;destination:"hand"|"field";reveal:boolean;optional:boolean;maxCost?:number};

const cards=(rawCards as CardDef[]).map(card=>compileCard(card) as CardDef);
type CardFaction="Dragão"|"Goblin"|"Gato"|"Vampiro"|"Recruta"|"Fênix";
/* Subtypes are compiled card data and may contain more than one value. */
const hasFaction=(card:Pick<CardDef,"page"|"subtypes">|undefined,faction:CardFaction)=>!!card&&hasSubtype(card,faction);
const deckDefs=[
 {id:"gimble",heroPage:2,start:3,end:25,name:"Gimble, Presenteado Sortudo",faction:"Natureza",color:"#2d9a58",style:"Dragões · crescimento",power:"Desvire um Dragão aliado",requirement:"2/4 Dragões",abilities:["I · Quando um Dragão deixa o campo, cure 1.","II · Uma vez por turno, desvire um Dragão aliado.","III · Na manutenção, seus Dragões recebem +1/+1."]},
 {id:"goblin",heroPage:26,start:27,end:49,name:"Sr. Goblin, o Mercador",faction:"Caos",color:"#8d45ce",style:"Goblin · Fura-Fila",power:"Compre ao perder um Goblin",requirement:"3/5 cartas no turno",abilities:["I · Ao perder um Goblin, compre 1 (uma vez/turno).","II · Compre 1 carta adicional na manutenção.","III · O primeiro Goblin do turno custa 0."]},
 {id:"uruk",heroPage:54,start:55,end:109,name:"Uruk, a Encantriz",faction:"Divino",color:"#378ed0",style:"Elementos · feitiços",power:"Ative o último elemento",requirement:"4/8 feitiços",abilities:["I · Fim do turno: ative o elemento do último feitiço.","II · Seu primeiro feitiço custa 1 a menos.","III · Duplique o último feitiço do seu turno."]},
 {id:"tifon",heroPage:110,start:111,end:128,name:"Tifon, a Peste",faction:"Vazio",color:"#353943",style:"Último Suspiro",power:"Compre quando um aliado morrer",requirement:"3/7 mortes",abilities:["I · Quando uma criatura sua morrer, compre 1 (máx. 3).","II · Último Suspiro aliado causa 1 ao herói inimigo.","III · Seus Últimos Suspiros são ativados duas vezes."]},
 {id:"saymon",heroPage:129,start:130,end:151,name:"Saymon, o Primeiro",faction:"Neutro",color:"#777d86",style:"Vampiros · Roubo de Vida",power:"Perca 2: cause 1",requirement:"3/5 perdas de vida",abilities:["I · Pague 2 de vida: cause 1 a um alvo (uma vez/turno).","II · Pague 2 de vida: dê Roubo de Vida a uma criatura.","III · Custos de vida não podem reduzir sua vida abaixo de 1."]},
 {id:"tessalia",heroPage:152,start:153,end:179,name:"Tessália, a Mão de Ferro",faction:"Ordem",color:"#d54a45",style:"Comandante · formação",power:"Fortaleça o centro",requirement:"3/6 ataques",abilities:["I · Seu Comandante tem +2 de Ofensividade e sem ele, você não pode atacar.","II · Seu Comandante tem Atropelar e recebe +3.","III · Uma vez/turno, outra criatura pode morrer pelo Comandante."]},
 {id:"quarion",heroPage:180,start:181,end:210,name:"Quarion Siannodel",faction:"Ordem",color:"#c84642",style:"Primeiro Ato · valor",power:"Recupere a primeira criatura",requirement:"2/4 nomes diferentes",abilities:["I · Ao ativar Primeiro Ato, compre 1 (uma vez/turno).","II · A primeira criatura que morrer no seu turno volta à mão.","III · O primeiro Primeiro Ato do turno é ativado novamente."]},
 {id:"rasmus",heroPage:211,start:212,end:254,name:"Rasmus, Barista do Tempo",faction:"Divino",color:"#378ed0",style:"Gatos · Café",power:"Cure ao causar dano",requirement:"5/7 Gatos",abilities:["I · Após 10 Cafés, crie um Café Especial.","II · Quando um Gato causar dano a um jogador, cure 1.","III · Gatos também podem ocupar espaços de não-criaturas."]},
 {id:"ngoro",heroPage:255,start:256,end:272,name:"Ngoro, o Investigador",faction:"Caos",color:"#7949b5",style:"Investigar · Triturar",power:"Investigue o deck alvo",requirement:"5/10 Pistas",abilities:["I · Ao Investigar, ganhe 1 Pista; no início, Investigue 1.","II · Gaste 2 Pistas: compre 1 ou triture 2.","III · Gaste 3 Pistas: dê Furtivo a uma criatura aliada."]},
 {id:"zayan",heroPage:273,start:274,end:290,name:"Zayan, a Revolucionária",faction:"Ordem",color:"#cf4c45",style:"Criaturas sem efeito",power:"Fortaleça uma criatura",requirement:"3/4 constantes",abilities:["I · No combate, uma criatura sem efeito recebe +1/+1.","II · Outra criatura pode ser destruída no lugar de uma sem efeito.","III · Criaturas sem efeito recebem Investida."]},
 {id:"natureza",heroPage:291,start:292,end:309,name:"Campeão de Natureza",faction:"Natureza",color:"#289455",style:"Marcadores de ação",power:"Distribua marcadores",requirement:"10/20 marcadores",abilities:["I · Uma vez/turno, dê 2 marcadores a até duas constantes.","II · Ao colocar marcadores, coloque um adicional.","III · Remova 4 marcadores: vire uma criatura alvo."]},
] as const;
type DeckId=typeof deckDefs[number]["id"];
type DeckDef=typeof deckDefs[number];
const deckById=(id:string)=>deckDefs.find(d=>d.id===id)!;
const heroDisplayName=(id:string)=>({gimble:"Gimble",goblin:"Sr Goblin",uruk:"Uruk",tifon:"Tifon",saymon:"Saymon",tessalia:"Tessália",quarion:"Quarion",rasmus:"Rasmus",ngoro:"Ngoro",zayan:"Zayan",natureza:"Campeão de Natureza"}[id]??deckById(id).name.split(",")[0]);
const evolutionHint=(id:string,level:number)=>{const hints:Record<string,string[]>={gimble:["Reúna Dragões e faça a ninhada crescer","Alcance a marca de 2 Dragões em jogo","Domine 4 Dragões para o ápice"],goblin:["Jogue cartas em sequência para alimentar o mercado","Atinja 3 cartas jogadas no mesmo turno","Complete 5 cartas no turno para a evolução final"],uruk:["Conjure feitiços para carregar os elementos","Conjure 4 feitiços e canalize o próximo elemento","Conjure 8 feitiços para dominar os elementos"],tifon:["Veja aliados tombarem e transforme perdas em vantagem","Registre 3 mortes aliadas","Registre 7 mortes para liberar o Último Suspiro"],saymon:["Perca vida em eventos distintos neste turno","Acumule 3 marcadores temporários neste turno","Acumule 5 marcadores temporários neste turno"]};return hints[id]?.[Math.min(2,Math.max(0,level-1))]??"Cumpra o marco exibido para liberar o próximo poder"};
/* Interpreted summaries keep the evolution tooltip concise and readable. */
const evolutionCriterionSummary=(id:string)=>({gimble:"Controle simultaneamente a quantidade indicada de Dragões.",goblin:"Jogue a quantidade indicada de cartas no mesmo turno; o progresso reinicia no próximo.",uruk:"Conjure feitiços ao longo da partida para dominar os elementos.",tifon:"Acumule mortes de criaturas aliadas ao longo da partida.",saymon:"Cada evento de perda de vida concede 1 marcador até o fim do turno; o progresso reinicia no próximo.",tessalia:"Declare ataques com a criatura no espaço central, seu Comandante.",quarion:"Controle simultaneamente criaturas com nomes diferentes e Primeiro Ato.",rasmus:"Controle simultaneamente a quantidade indicada de Gatos.",ngoro:"Acumule Pistas por meio de Investigar; Pistas gastas deixam de contar.",zayan:"Controle simultaneamente constantes sem texto de efeito.",natureza:"Acumule marcadores de ação nas suas constantes."}[id]??"Cumpra o objetivo do herói para liberar o próximo nível.");
/* Listas de teste fornecidas pelo autor. O número é a página/arte canônica do catálogo,
   portanto a composição e a ilustração deixam de depender de intervalos aproximados. */
const suppliedDeckPages:Partial<Record<DeckId,Array<[number,number]>>>= {
 gimble:[[3,3],[4,3],[5,3],[6,3],[7,3],[8,3],[9,2],[10,2],[11,2],[12,3],[13,3],[14,2],[15,3],[17,3],[18,2],[16,2],[20,3],[21,2],[22,2]],
 goblin:[[28,2],[29,3],[27,3],[30,2],[33,2],[32,2],[31,3],[34,3],[35,3],[36,3],[48,3],[42,3],[43,3],[44,3],[45,3],[46,3],[47,2],[41,3]],
 uruk:[[77,3],[78,3],[76,2],[80,2],[79,3],[64,2],[69,2],[55,3],[56,3],[68,3],[67,2],[63,2],[61,3],[65,2],[57,2],[75,2],[62,2],[58,1],[66,1],[60,2],[70,2],[59,2]],
 tifon:[[111,3],[112,3],[114,3],[113,3],[115,3],[116,3],[117,3],[118,3],[119,2],[120,2],[125,3],[122,3],[123,3],[121,3],[124,3],[127,2],[126,2],[128,2]],
 saymon:[[130,3],[131,3],[132,3],[133,3],[135,2],[134,3],[136,3],[138,2],[137,3],[140,3],[139,3],[145,3],[146,2],[143,2],[144,3],[142,2],[147,2],[141,2],[148,2]],
 tessalia:[[164,2],[165,2],[166,2],[167,3],[171,3],[169,2],[168,2],[172,3],[173,2],[174,2],[175,2],[176,2],[158,2],[161,2],[157,2],[160,2],[162,2],[159,2],[156,2],[154,2],[153,2],[155,2],[163,2]],
 quarion:[[184,3],[189,3],[186,3],[188,3],[183,3],[190,3],[187,3],[185,3],[182,2],[193,2],[197,2],[194,2],[196,2],[195,2],[192,2],[153,2],[150,2],[151,3],[191,2],[181,2]],
 ngoro:[[256,3],[257,3],[260,3],[259,3],[262,3],[258,3],[261,3],[264,3],[263,3],[266,3],[265,3],[269,3],[267,3],[268,3],[270,3],[271,2],[272,2]],
};
/* Cartas complexas ainda não liberadas não entram em nenhum deck jogável. */
const disabledDeckCardIds=new Set(["p200","p201","p203","p206","p207","p209","p210"]);
const allFor=(id:string)=>{const d=deckById(id);return cards.filter(c=>c.page>=d.start&&c.page<=d.end&&!c.hero)};
const poolFor=(id:string)=>{const supplied=suppliedDeckPages[id as DeckId];return supplied?supplied.map(([page])=>cards.find(card=>card.page===page)).filter((card):card is CardDef=>!!card&&!card.imageCard&&!disabledDeckCardIds.has(card.id)):allFor(id).filter(c=>!c.imageCard&&!disabledDeckCardIds.has(c.id))};
const extraFor=(id:string)=>allFor(id).filter(c=>c.imageCard&&!disabledDeckCardIds.has(c.id));
const buildDeck=(id:string)=>{const supplied=suppliedDeckPages[id as DeckId];if(supplied)return supplied.flatMap(([page,quantity])=>{const card=cards.find(candidate=>candidate.page===page);return card&&!disabledDeckCardIds.has(card.id)?Array.from({length:quantity},(_,copy)=>({...card,id:`${card.id}-${id}-${copy}-${uid()}`})):[]});const pool=poolFor(id),out:CardDef[]=[];let copy=0;while(out.length<49){for(const c of pool){if(out.length===49)break;out.push({...c,id:`${c.id}-${copy}`})}copy++}return out};
const shuffle=<T,>(source:T[])=>{const a=[...source];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
let idSequence=0;const uid=()=>globalThis.crypto?.randomUUID?.()??`hh-${Date.now().toString(36)}-${(++idSequence).toString(36)}-${Math.random().toString(36).slice(2,8)}`;
const log=(g:Game,text:string,tone="")=>{g.log.unshift({id:uid(),text,tone});g.events++};
const makePlayer=(heroId:string,startingLife=30):Player=>{const deck=shuffle(buildDeck(heroId));return{heroId,level:1,heroXP:0,levelUpsThisTurn:0,life:startingLife,lifeLostThisTurn:0,lifeLossEvents:0,maxEnergy:0,energy:0,reserve:0,deck:deck.slice(7),extraDeck:extraFor(heroId),hand:deck.slice(0,7),board:[],support:[],terrain:null,grave:[],obscuro:[],cardsPlayed:0,turnCardsPlayed:0,goblinTurnCardsPlayed:0,turnSpellsPlayed:0,spellsPlayed:0,coffeeSpells:0,damageDealt:0,turnDeaths:0,abilityUses:{},pendingTranqueira:false,nextCardDiscount:0,nextNonCreatureDiscount:0,nextSpellDiscount:0,nextSummonPaysLife:false,nextCreaturePaysLife:false,catsEnteredThisTurn:0}};
const start=(a:string,b:string,active:0|1=0,startingLife=30):Game=>({players:[makePlayer(a,startingLife),makePlayer(b,startingLife)],active,phase:"manutencao",round:1,log:[{id:"start",text:"A batalha por Hemsfell começou.",tone:"system"}],winner:null,selectedAttackers:[],events:1,combatAction:null,pendingResponse:null,turnDeadline:null});
const firstFreeSlot=(units:Unit[])=>Array.from({length:5},(_,slot)=>slot).find(slot=>!units.some(unit=>unit.slot===slot));
const asUnit=(c:CardDef,slot=0):Unit=>({...c,revealed:undefined,uid:uid(),slot,damage:0,bonusAtk:0,bonusHp:0,attackedThisTurn:false,exhausted:false,summoning:!c.tags.some(tag=>cleanName(tag)==="investida"),frozen:false,stunned:false,suffocated:false,immobilized:false,markers:0,defenseUses:0});
const supportNumbers=(p:Player|undefined,u:Unit)=>{if(!p||u.suffocated)return{atk:0,hp:0};let atk=0,hp=0;for(const source of [...p.board,...p.support]){if(source.uid===u.uid||source.suffocated||Math.abs(source.slot-u.slot)!==1||!/\bSuporte\b/i.test(source.text)&&!source.tags.some(tag=>cleanName(tag)==="suporte"))continue;if((u.modifiers||[]).some(modifier=>modifier.duration==="support"&&modifier.sourceId===source.uid))continue;const match=source.text.match(/Suporte\s*:?\s*([+-]?\d+)\s*\/\s*([+-]?\d+)/i);if(match){atk+=Number(match[1]);hp+=Number(match[2])}}return{atk,hp}};
const equipmentNumbers=(p:Player|undefined,u:Unit)=>{if(!p||u.suffocated)return{atk:0,hp:0};let atk=0,hp=0;for(const source of p.support.filter(card=>card.attachedTo===u.uid&&!card.suffocated)){if(u.modifiers?.some(modifier=>modifier.sourceId===source.uid))continue;if(source.page===197&&["recruta exibido","recruta iludido"].includes(cleanName(effectiveCreatureName(p,u))))continue;const pair=source.text.match(/recebe(?:\s+também|\s+apenas)?\s*([+-]?\d+)\s*\/\s*([+-]?\d+)/i);if(pair){atk+=Number(pair[1]);hp+=Number(pair[2]);continue}const attack=source.text.match(/recebe\s*([+-]?\d+)\s*(?:de\s*)?Ofensividade/i),vitality=source.text.match(/recebe\s*([+-]?\d+)\s*(?:de\s*)?Vitalidade/i);if(attack)atk+=Number(attack[1]);if(vitality)hp+=Number(vitality[1])}return{atk,hp}};
const isCommander=(p:Player|undefined,u:Unit)=>!!p&&p.heroId==="tessalia"&&u.slot===2&&!u.suffocated;
const statModifiers=(p:Player|undefined,u:Unit)=>{const keep=(value:number)=>u.suffocated?Math.min(0,value):value,support=supportNumbers(p,u),equipment=equipmentNumbers(p,u),structured=(u.modifiers||[]).reduce((sum,item)=>({atk:sum.atk+keep(item.attack||0),hp:sum.hp+keep(item.health||0)}),{atk:0,hp:0}),catBonus=p&&hasFaction(u,"Gato")?p.board.filter(card=>card.page===218&&!card.suffocated).length:0,commanderBonus=isCommander(p,u)?(p!.level>=2?3:2):0;return{atk:keep(u.bonusAtk||0)+keep(u.temporaryAtk||0)+structured.atk+support.atk+equipment.atk+(u.suffocated?0:catBonus+commanderBonus),hp:keep(u.bonusHp||0)+keep(u.temporaryHp||0)+structured.hp+support.hp+equipment.hp+(u.suffocated?0:catBonus)}};
const currentHp=(u:Unit,p?:Player)=>{const modifier=statModifiers(p,u);return(u.hp||1)+modifier.hp-u.damage};
const currentAtk=(u:Unit,p?:Player)=>{const modifier=statModifiers(p,u);return u.frozen?0:Math.max(0,(u.atk||0)+modifier.atk)};
const markCreatureDamage=(source:CardDef|Unit,damagedOwner:0|1)=>{if(!("uid" in source))return;source.damagedOwnersThisTurn||=[];if(!source.damagedOwnersThisTurn.includes(damagedOwner))source.damagedOwnersThisTurn.push(damagedOwner)};
const hasKeyword=(p:Player|undefined,u:Unit,keyword:string)=>{if(u.suffocated)return false;const wanted=cleanName(keyword),matches=(value:string)=>cleanName(value).includes(wanted),pairedDuelist=u.page===171?p?.board.some(card=>card.page===172&&!card.suffocated):u.page===172?p?.board.some(card=>card.page===171&&!card.suffocated):false;if((u.page===171||u.page===172)&&(wanted==="barreira magica"||wanted==="robusto"))return !!pairedDuelist;if(wanted==="atropelar"&&isCommander(p,u)&&p!.level>=2)return true;if(u.tags.some(tag=>cleanName(tag)===wanted)||u.temporaryTags?.some(tag=>cleanName(tag)===wanted)||u.grantedKeywords?.some(matches)||matches(u.text))return true;if(!p)return false;return p.support.some(source=>!source.suffocated&&(source.attachedTo===u.uid||Math.abs(source.slot-u.slot)===1&&/\bSuporte\b/i.test(source.text))&&matches(source.text))||!!p.terrain&&!p.terrain.suffocated&&matches(p.terrain.text)};
const defenderCapacity=(p:Player,u:Unit)=>{const match=(u.text+" "+p.support.filter(x=>x.attachedTo===u.uid).map(x=>x.text).join(" ")).match(/Defensor\s*(\d+)/i);return match?Number(match[1]):1};
const cardElement=(c:CardDef)=>cleanName(c.name)==="maestria elemental"?undefined:c.text.match(/Elemento:\s*(Fogo|Água|Terra|Ar)/i)?.[1] as ElementName|undefined;
const elementChainFrom=(c:CardDef):Player["elementChain"]=>ruleElementalChainFrom(cardElement(c)) as Player["elementChain"];
/* Investigate preserves the top card, archives the rest and dispatches every revealed-card trigger. */
const investigate=(g:Game,investigator:Player,target:Player,n:number)=>{
 const viewed=target.deck.splice(0,n);if(!viewed.length){log(g,"Não havia cartas para Investigar.","manual");return}
 const revealed=viewed[0],archived=viewed.slice(1);target.deck.unshift(revealed);target.deck.push(...archived);
 if(investigator.heroId==="ngoro")investigator.heroXP+=1;
 investigator.board.filter(unit=>unit.page===261&&revealed.type==="Criatura"&&!unit.suffocated).forEach(unit=>{unit.temporaryAtk=(unit.temporaryAtk||0)+1;log(g,`Espião Infiltrado recebeu +1/+0 ao revelar ${revealed.name}.`,"effect")});
 investigator.board.filter(unit=>unit.page===262&&revealed.type==="Feitiço"&&!unit.suffocated&&g.active===owner).forEach(unit=>{const milled=target.deck.splice(1,1);if(milled.length)target.grave.push(...milled);log(g,`Nmali triturou ${milled.length} carta ao revelar um Feitiço.`,"effect")});
 investigator.support.filter(unit=>unit.page===272&&!unit.suffocated).forEach(unit=>{if(revealed.type==="Criatura"){const milled=target.deck.splice(1,1);if(milled.length)target.grave.push(...milled);log(g,"Base de Investigação triturou 1 carta por revelar uma Criatura.","effect")}else if(revealed.type==="Artefato"){investigator.energy=Math.min(10,investigator.energy+1);log(g,"Base de Investigação concedeu 1 de energia por revelar um Artefato.","energy")}else if(revealed.type==="Encanto"){draw(g,investigator);log(g,"Base de Investigação comprou 1 carta por revelar um Encanto.","effect")}});
 log(g,`Investigar ${n}: ${revealed.name} foi revelada no topo${archived.length?` e ${archived.length} carta(s) foram Arquivadas no fundo`:""}.`,"effect")
};
